### ISSUE TITLE
Display record links in the Designer pane

### ISSUE THREAD

**Issue by wedobetter** [surrealdb/surrealist#100]
**Describe your feature request**
It'd be very useful to see record links displayed in the Designer pane same as edges. 
Maybe use unidirectional arrow for record links and bidirectional arrow for edges. 

**Are you willing to contribute this feature?**
I'd love to but not a Rust developer

**Related pull request (if applicable)**
N/A

**Comment by MatthewAry** [comment]
Yup, it would be great to directed and undirected edges displayed. It would be nice if the edges linked up to the table header and to the record field so you can see more clearly the context of the relationship.
