### ISSUE TITLE
Handle Websocket error: ERR_NETWORK_IO_SUSPENDED

### ISSUE THREAD

**Issue by ntorrey** [surrealdb/surrealist#141]
**Describe the bug**
After waking my computer from sleep, Surrealist seems to be still connected, but even after refreshing the connection nothing works. There's an error in the console: `WebSocket connection to 'wss://.../rpc' failed: Error in connection establishment: net::ERR_NETWORK_IO_SUSPENDED`. Closing and opening Surrealist fixes the problem.

**To Reproduce**
Open Surrealist and let your computer go to sleep. Wake the computer up and see if Surrealist still works.

**Expected behavior**
I expect Surrealist to either:
1. Just continue working even after the computer wakes from sleep, as if nothing happened. Or,
2. Give a visual indication in the UI that it is no longer connected with an option to refresh the connection - and the refresh action should reconnect successfully.

**Environment:**
 - Operating System: Windows 10
 - Surrealist Version: 1.11.0
 - SurrealDB Version: surrealdb-1.0.0+20231019.f185c59

**Comment by macjuul** [comment]
This should no longer happen in Surrealist 2.0. If you do encounter this problem feel free to re-open this issue
