### ISSUE TITLE
Option to add "futures"

### ISSUE THREAD

**Issue by Icaruk** [surrealdb/surrealist#144]
It woud be cool if [future](https://surrealdb.com/docs/surrealql/datamodel/futures) field could be implemented.

![image](https://github.com/StarlaneStudios/Surrealist/assets/10779469/a179bd91-e765-4cca-a359-9e8199a84fe8)

**Comment by Icaruk** [comment]
> Could you elaborate on what you would like to see changed in Surrealist?
> 
> Futures should already be available to use in Surrealist and they should be highlighted correctly.

Is not highlighted and I was not sure about where should I write my `<future>{ ... }`.
Now with more experience I have no longer this problem, but at beginning I would've liked something like "Input your future here" with the boilerplate syntax.

![image](https://github.com/StarlaneStudios/Surrealist/assets/10779469/d3f12240-c56c-40a8-9789-f9e614ddf648)

**Comment by macjuul** [comment]
It would be difficult to treat futures different than other field types, however if you press the wrench on the right it will open a larger editor with highlighting

**Comment by Icaruk** [comment]
> It would be difficult to treat futures different than other field types, however if you press the wrench on the right it will open a larger editor with highlighting

No highlighting for me :(

![image](https://github.com/StarlaneStudios/Surrealist/assets/10779469/058f7a17-4d5e-4bfb-94b9-ad18dc61bccc)

**Comment by macjuul** [comment]
This has been improved in Surrealist 2.0 and highlighting is now available in relevant input fields. There may still be some minor future related highlighting issues we are looking to fix
