### ISSUE TITLE
Endless loop when saving changes to table edited in "Designer" mode on the web application

### ISSUE THREAD

**Issue by OTheNonE** [surrealdb/surrealist#145]
**Describe the bug**
This bug happens on the browser version of Surrealist. When i am in designer mode and press "save changes" on my tables, the "engine" goes into a endless loop. The endless loop can be seen in the Console, as the application keeps console.log(...)'ing.

**To Reproduce**
1. Go to [The Surrealist Web App](https://surrealist.app/designer)
2. Open the Console on the Inspect page.
3. Create and make changes to a table.
4. Press "Save Changes".
5. You will now see an endless console.log'ing.

**Environment (you can view the current version under Settings):**
 - Operating System: Windows
 - Surrealist Version: 1.11.0

**Comment by QuantumTarantino** [comment]
Same problem on Linux, version 1.11.0

**Comment by macjuul** [comment]
This should be fixed in Surrealist 2.0, however if you still encounter this issue feel free to re-open or create a new issue.
