### ISSUE TITLE
Some tables in Designer tab do not appear properly.

### ISSUE THREAD

**Issue by eminfedar** [surrealdb/surrealist#151]
**Describe the bug**
I have designed a database in Designer tab. One table has 10 fields and Show Less/Show More button appeared. But the table content are not appearing properly and it is staying behind under another table.

My tables are connected to one Relation graph. One in, multiple out tables.

![image](https://github.com/StarlaneStudios/Surrealist/assets/14258668/ce63e3d8-1395-41b9-9a05-546cc5c802d9)

The table with 10 fields is staying behind under another table. Same after expanded too.

**To Reproduce**
1. Open Designer tab
2. Add 4 Tables, one of them has 10 fields.
3. Add 1 Relation table, put one table in `in` field, others in `out` field.
4. 10 field table in the `out` side of the relation does not appear properly on Designer page. It is going under the other table.

**Expected behavior**
All tables must be shown properly and without getting mixed.

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: Linux (Pardus 23, Debian 12 Based) 
 - Surrealist Version [e.g. 1.2.0]: 1.11.0
 - SurrealDB Version [execute "surreal version"]: 1.0.0

**Comment by macjuul** [comment]
The designer view has been overhauled in Surrealist 2.0 including a new layout algorithm, so overlapping tables will no longer be possible. Additionally, tables with a large amount of fields can now be scrolled instead.
