### ISSUE TITLE
New to SurrealDB.  Should connect with default port 8000

### ISSUE THREAD

**Issue by paulm17** [surrealdb/surrealist#158]
**Describe the bug**
Only put 127.0.0.1 in the endpoint.

**To Reproduce**
Open Surrealist, create a new connection and put 127.0.0.1 in the endpoint url.

**Expected behavior**
Either output in the console that no port has been supplied or default to 8000 if hasn't been supplied.

**Environment (you can view the current version under Settings):**
 - Mac OS
 - Surrealist Version [e.g. 1.2.0]: 1.11.1
 - SurrealDB Version [execute "surreal version"]: 1.0

**Comment by macjuul** [comment]
I like the idea of automatically inferring port 8000, I'll consider implementing this into the next release

**Comment by macjuul** [comment]
After further consideration I have decided not to implement this behaviour as we cannot guarantee a database always runs on port 8000. For example, when running SurrealDB behind a reverse proxy it may be accessible using other ports instead.

I will continue to improve the connection management in Surrealist and make sure the connection management process is made clear.

Note that unlike the port, omitting the `/rpc` path is supported.
