### ISSUE TITLE
Permissions in 'Designer' view are incorrect

### ISSUE THREAD

**Issue by ntorrey** [surrealdb/surrealist#159]
**Describe the bug**
The permissions shown for each table in the 'Designer View' are incorrect. They are different from the permissions shown when running 'INFO FOR DB' (Edit: It seems that the 'INFO FOR TABLE ...' command may not be working correctly/works differently in beta 1.1.0. So maybe this is a surrealdb issue?)

**To Reproduce**
1. Go to the 'Designer' view.
2. Check to see if permissions are correct.

**Expected behavior**
I expect the permissions settings shown in the 'Designer' view to correspond with the result of running 'INFO FOR DB' in the query editor.

**Environment (you can view the current version under Settings):**
 - Operating System: Windows 11 Home
 - Surrealist Version: 1.11.1 (For beta 1.1.0)
 - SurrealDB Version: surrealdb-1.1.0-beta.1+20231212.2d0d23b

**Comment by macjuul** [comment]
This should be resolved in Surrealist 2.0. If you still encounter this problem feel free to re-open this issue or open a new issue.
