### ISSUE TITLE
Add geo data visualisation

### ISSUE THREAD

**Issue by silvergasp** [surrealdb/surrealist#160]
**Describe your feature request**
I'd love to be able to visualise [geographical queries](https://docs.surrealdb.com/docs/surrealql/datamodel/geometries) using surrealist. Perhaps using something like [kepler.gl](https://kepler.gl).

**Are you willing to contribute this feature?**
Sort of, I'm happy to hack something together, but I'm not really a javascript/typescript dev, so it'll take me a really long time to put something together that is nice and polished.

**Related pull request (if applicable)**
N/A

**Comment by macjuul** [comment]
This has been implemented in the form of the Geometry explorer found in the Designer view, and by using the table result mode in the Query view
