### ISSUE TITLE
AppImage (v.1.11.1) does not launch on Wayland

### ISSUE THREAD

**Issue by horvbalint** [surrealdb/surrealist#162]
**Describe the bug**
Since the latest Surrealist version (v.1.11.1) the .appImage launchers do not start when using a Wayland session on Linux.
Launching from the terminal produces the following error:
```
(surrealist:8935): GLib-GIO-ERROR **: 10:12:54.387: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)
```
Launching the AppImage in an X11 session works as expected.
Launching with the `GDK_BACKEND=x11` env variable fixes the error on Wayland as well.
Previous versions did not have this error and worked just fine under Wayland out of the box.

I searched for a related issue in the Tauri github but did not found anything.
I foud the `GDK_BACKEND=x11` solution in multiple threads discussing a similar issue:

- https://github.com/Ultimaker/Cura/issues/12776
- https://github.com/powenn/AltServer-LinuxGUI/issues/3

**To Reproduce**
1. Download the v.1.11.1 version .appImage launcher
2. Make it executable
3. Attempt to launch it

**Expected behavior**
The launcher should start like the previous versions.

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: Fedora Linux 39
 - Surrealist Version [e.g. 1.2.0]: 1.11.1
 - SurrealDB Version [execute "surreal version"]: 1.0.1+20231214.c992c9c.dirty for linux on x86_64

**Comment by agfp** [comment]
Issue reproduced on openSUSE Tumbleweed.

**Comment by macjuul** [comment]
I don't currently have the understanding or resources to look into this issue myself, so any contributions made to fix and improve Wayland support are greatly appreciated

**Comment by horvbalint** [comment]
Yes! I forgot to write here so thanks! I think only that one version did not work.
