### ISSUE TITLE
Large numbers being floored

### ISSUE THREAD

**Issue by UwUDev** [surrealdb/surrealist#168]
**Describe the bug**
Large numbers *(i guess above an u32)* get their last decimal floored to 0

***Edit**: Sometime it can be more than one decimal*

**To Reproduce**
1. Create a sample table
2. put a lage numer such as `574317759736053768`
3. Make a querry that get this value such as `select test_column from test_table`
4. You could see that the value will be `574317759736053760` instead of `574317759736053768`

**Expected behavior**
Get the right number

**Environment (you can view the current version under Settings):**
 - Operating System : Windows 10 1809 *(same issue on 21h2)*
 - Surrealist Version : 1.11.2
 - SurrealDB Version : 1.1.1
 
 **Example**
 Expected response: 
![image](https://github.com/StarlaneStudios/Surrealist/assets/61664271/e483ac8b-7afc-4549-9538-882e0164ef8f)

Got: 
![image](https://github.com/StarlaneStudios/Surrealist/assets/61664271/037e9e7b-749b-4fa0-96d0-d482df4a3e5d)

**Comment by UwUDev** [comment]
The issue seems to come from`JSON.parse()` 
![image](https://github.com/StarlaneStudios/Surrealist/assets/61664271/67978056-f08e-4aad-991f-4f0b60b1bb44)


Maybe there is a better lib to parse json in TS

**Comment by macjuul** [comment]
This is an extremely tricky issue to solve, as even revivers won't result in the correct outcome (See https://jsoneditoronline.org/indepth/parse/why-does-json-parse-corrupt-large-numbers/).

I'll continue to investigate possible solutions for this issue though.

**Comment by macjuul** [comment]
This has now been resolved in Surrealist 2.0 when previewing responses in SurrealQL, as unlike JSON, SurrealQL does support 64-bit numbers.

We are still rolling this out to other editors throughout Surrealist in the coming releases
