### ISSUE TITLE
weird formatted tables name leads to empty explorer, designer, authentification sections (but querying works)

### ISSUE THREAD

**Issue by nathanschwarz** [surrealdb/surrealist#170]
**Describe the bug**
- the UI shows that the connection is successful
- When running queries, data is correctly fetched
- Nothing is shown in the explorer / designer / authentification sections

I tried on my old intel mac with the same configuration and DB and it works perfectly.

**To Reproduce**

Just run on a M2 mac and hit the explorer view

**Expected behavior**

tables and columns should be visible in the explorer views

**Environment (you can view the current version under Settings):**
 - Operating System : mac os 14.2.1
 - Surrealist Version [e.g. 1.2.0]: 1.11.3
 - SurrealDB Version [execute "surreal version"]: 1.1.1

**Comment by singersbalm** [comment]
the m2 Mac isn't the issue. it works on mine

**Comment by nathanschwarz** [comment]
Okay, I noticed by running the `INFO FOR DB` query that one of the table was weirdly formatted on my M2 database: "`\\`attributes \\``" (a problem with the python driver somewhere). I had to remove it through the python driver (it wouldn't work with surrealist or the CLI).
Once the table was removed it was working again.
