### ISSUE TITLE
Explorer functionality crashes the app

### ISSUE THREAD

**Issue by careerlister** [surrealdb/surrealist#174]
**Describe the bug**
When I load the app then go from Query to Explorer the app crashes.   

I am on => Surrealdb 1.1.0.   Surrealist Version 1.11.3 (20240125.225857).   OSX 12.0.1   M1 MacBook Pro

Error on the Explorer => 

Unexpected Application Error!

e.at is not a function. (In 'e.at(-1)', 'e.at' is undefined)

lXt@http://localhost:18982/assets/index-d19b4f02.js:1264:4179783
uXt@http://localhost:18982/assets/index-d19b4f02.js:1264:4180135
DJ@http://localhost:18982/assets/index-d19b4f02.js:88:188993
RDe@http://localhost:18982/assets/index-d19b4f02.js:90:241851
IDe@http://localhost:18982/assets/index-d19b4f02.js:90:237552
IZe@http://localhost:18982/assets/index-d19b4f02.js:90:237475
_O@http://localhost:18982/assets/index-d19b4f02.js:90:237325
Nq@http://localhost:18982/assets/index-d19b4f02.js:90:233672
Uae@http://localhost:18982/assets/index-d19b4f02.js:90:234478
Uae@[native code]
d_@http://localhost:18982/assets/index-d19b4f02.js:88:172697
@http://localhost:18982/assets/index-d19b4f02.js:90:231990

**Comment by macjuul** [comment]
This appears to be caused by a browser compatibility issue. I'll fix the affected code to prevent it from happening.

Additionally, it might be possible to fix this issue directly if you make sure your version of Safari is up-to-date (at least 15.4)

**Comment by careerlister** [comment]
Ok.  I have upgraded my computer so that it has the updated Safari and the Explorer is now working.  Thank you for the info and making Surrealist!
