### ISSUE TITLE
The Explorer view show table columns bug

### ISSUE THREAD

**Issue by Mczeno** [surrealdb/surrealist#179]
**Describe the bug**
when switch different tables in Expolrer view，the record explorer show all table columns。

**To Reproduce**
1. Go to 'Explorer'
2. Click and switch differenct table
3. See all columns on Record Explorer

**Expected behavior**
Record Explorer only show chosen table columns and records;

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: MacOS 14.2.1
 - Surrealist Version [e.g. 1.2.0]: 1.11.4
 - SurrealDB Version [execute "surreal version"]: 1.2.1

**Comment by yassinrais** [comment]
Same 👍🏻

**Comment by macjuul** [comment]
Thank you for reporting this issue! I understand this is an annoying issue so I'll work on a fix in due course

**Comment by macjuul** [comment]
This issue has been fixed in a recent release of Surrealist
