### ISSUE TITLE
In-browser sandbox: Embedded functions are not enabled

### ISSUE THREAD

**Issue by orimay** [surrealdb/surrealist#181]
**Describe your feature request**
In-browser sandbox doesn't allow to use embedded functions, throws error `Embedded functions are not enabled`. It would've been nice to have access to this functionality. Thank you!

**Are you willing to contribute this feature?**
I am not willing to contribute

**Comment by macjuul** [comment]
Unfortunately this isn't currently supported as the JavaScript engine doesn't compile to WebAssembly

**Comment by orimay** [comment]
@macjuul It now seems to be possible:
```ts
import {
  Surreal,
  type Emitter,
  type Engine,
  type EngineEvents,
} from 'surrealdb.js';
import { surrealdbWasmEngines } from 'surrealdb.wasm';

const db = new Surreal({
  engines: surrealdbWasmEngines({
    strict: false,
    capabilities: {
      guest_access: true,
      functions: true,
      network_targets: true,
    },
  }) as Record<string, new (emitter: Emitter<EngineEvents>) => Engine>,
});
```

**Comment by macjuul** [comment]
The `functions` capability refers to regular built-in and SurrealQL functions, not embedded scripting functions written in JavaScript. I cannot guarantee these will ever be supported due to the complexity behind exposing these through WebAssembly

**Comment by orimay** [comment]
Oh, that's a pity. Thank you!
