### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by GimmeDataNow** [surrealdb/surrealist#182]
**Describe your feature request**
There a few features / changes I'd like to request to make the UX better (imo).

> Designer

- [ ] Move the 'Unsaved changes' pop-up from the bottom right corner, because the 'Save changes' button is covered by it
- [ ] Allow the user to move tables via drag and drop. This would allow for the user to avoid some UI issues

> Query

- [ ] Allow for multiple 'Results' tabs similar to 'Query' tabs
- [ ] If the tables are defined as schema-full, provide some kind of autocomplete suggestions

**Are you willing to contribute this feature?**
No, I don't know react and I am still quite new to rust

**Related pull request (if applicable)**
NONE

**UI issues**
I'd like cases like these to move into the same column
![2024-03-05 16_03_35-surreal_prototype - Surrealist Designer](https://github.com/StarlaneStudios/Surrealist/assets/117273283/4566bc39-0112-4f6c-81d5-2bdf903486a5)

**Comment by macjuul** [comment]
Some of these suggestions are now implemented in Surrealist 2.0, and I will continue to improve the Surrealist user experience going forward
