### ISSUE TITLE
Add support for refreshing tables in Explorer and Designer views.

### ISSUE THREAD

**Issue by prabirshrestha** [surrealdb/surrealist#183]
If I'm connecting to a remote server and add a table programmatically via code Surrealist is not aware of it and this requires restarting the app. Add "Refresh" buttons such that it refreshes the list of tables.

**Comment by macjuul** [comment]
There is a refresh icon within the address bar which should do exactly what you're looking for. In a next release I plan on making this process a lot more seamless though

**Comment by macjuul** [comment]
Schema related resources are now refreshed automatically when performing certain actions within Surrealist, so you should no longer run into these issues.

Note that Surrealist does not react to schema changes made outside of the app. In these situations the easiest way to force Surrealist to fetch these changes is to switch between views
