### ISSUE TITLE
Application zoom support

### ISSUE THREAD

**Issue by knackstedt** [surrealdb/surrealist#184]
**Describe your feature request**
I would like Surrealist to support a zoom feature similar to pressing `CTRL+=` and `CTRL+-` so that when I open it on a high resolution display I can adjust it's physical size as I like. On my ultrawide monitor, it's hard to read since the text is on the smaller side, so I'd like to zoom things up 20-50%. 

**Are you willing to contribute this feature?**
Yes. I'd be willing to implement a global CSS zoom if I can get pointed in the right direction for where to put the setting.

**Related pull request (if applicable)**
N/A

**Comment by macjuul** [comment]
This is actually included in the 2.0 release! `Ctrl + -` and `Ctrl + =` can be used to zoom the entire window in or out, or alternative use the new Window scale slider in Settings > Appearance

<img width="646" alt="image" src="https://github.com/surrealdb/surrealist/assets/7606171/9ada0ef4-793a-42b4-adac-8892f2a4947b">

If you believe this not to be working feel free to open a new issue!

**Comment by wegerts** [comment]
Aaaahhh - yep. German Keyboard Layout -> `Ctrl + ß` , `Ctrl + ´`.
Thanks!
