### ISSUE TITLE
Fail to connect to a surreal instance exposed under a subpath

### ISSUE THREAD

**Issue by morganlefloch** [surrealdb/surrealist#191]
**Describe the bug**
It seams like Surrealist currently doesn't handle connecting to a surrealDB instance hosted under a path (e.g. http://myserver.dev/surrealdb). Looking at the web console, under  network tab, the websocket connection endpoint is ws://myserver.dev/rpc instead of ws://myserver.dev/surreal/rpc.

**To Reproduce**
1. Expose a surrealDB instance under a subpath
2. Try to connect to it with Surrealist
3. Connection error

**Expected behavior**
A connection to ws://example.com/surreal/rpc is expected instead of ws://example.com/rpc

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]:  Windows
 - Surrealist Version [e.g. 1.2.0]: 1.11.7
 - SurrealDB Version [execute "surreal version"]: v1.2.0

**Comment by macjuul** [comment]
This should be possible again as of a recent release

**Comment by EtienneBruines** [comment]
Are we sure this is fixed @macjuul ? The current version (v2.0.6 desktop) as well as the surrealist.app website seem to still connect to `/version` regardless of the (sub)path I add to the URL. (Instead of something like `/surreal/version` or `/surreal/rpc/version` or whatever the correct path would be.)

**Comment by macjuul** [comment]
My bad! I thought it was included in the previous release but it looks like I forgot to include it  😅 It will be in the next release though!

**Comment by EtienneBruines** [comment]
My apologies @macjuul - #251 was merged and available from 2.0.5 onwards. You did everything correctly :smile: 

Seems like my `haproxy` logic was wrong. (I was handling `/rpc` but not `/version` myself...)
