### ISSUE TITLE
New version breaks Anonymous connection to database

### ISSUE THREAD

**Issue by mjpc13** [surrealdb/surrealist#192]
**Describe the bug**
I am trying to connect to a local database without authentication, and Surrealist shows me the `Unsupported auth mode` msg, is this a desired behaviour? I don't have this bug on the version 1.11.7!

**To Reproduce**
1. Start a surreal db instance without the --auth flag
```
surreal start file://db/
```
2. Go to the Surrealist application (or on the web) 
3. Try to connect using the `Anonymous` authentication mode
4. Go to `Explorer` tab
5. See the `Unsupported auth mode` msg on the left.

**Expected behavior**
A successful connection to the database that does not require authentication.

**Environment (you can view the current version under Settings):**
 - Operating System -> Linux Ubuntu 20.04;
 - Surrealist Version -> 1.11.8: 
 - SurrealDB Version -> 1.4.0:

**Comment by macjuul** [comment]
This is expected as anonymous connections do not have access to `INFO FOR DB`, and thus cannot list out tables. This is an unfortunate limitation of the anonymous connection, and is mostly useful when using the query view.
