### ISSUE TITLE
Surrealist Windows version crashes after connection is created

### ISSUE THREAD

**Issue by JohnKinyanjui** [surrealdb/surrealist#195]
**Describe the bug**
Surrealist windows crashes after creating a new connection and using designer note this was done on a fleshly installed surrealist with no data saved.

**To Reproduce**
1. Create a new connection
2. Try any feature in surrealist also make sure the surrealist is freshly installed.

**Expected behavior**
The Windows app crashes

**Environment:**
```
![Screenshot 2024-04-23 185022](https://github.com/surrealdb/surrealist/assets/52638680/8ee8e3b3-528e-4b6f-a0d5-2e7e89024a66)

surreal 1.4.2
```
![Screenshot 2024-04-23 185022](https://github.com/surrealdb/surrealist/assets/52638680/2ea996f5-a98d-4600-a62e-8e8117a0e358)

**Comment by TimMensch** [comment]
Funny, I just repro'ed this one.

I tried to connect to a brand new localhost database running from the latest Docker SurrealDB, set with `--auth` and a root user and password.

Docker compose file looks like:

```
services:
  surrealdb:
    env_file:
      - path: ./.env
    entrypoint:
      - /surreal
      - start
      - --auth
      - -l
      - debug
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000
```

And the `.env` has:

```
SURREAL_USER=citeserver
SURREAL_PASS=*******
```

I tried the Windows app because the web app keeps failing to log in. The CLI works with the credentials from the `.env` file though.

**Comment by macjuul** [comment]
@TimMensch did you also encounter this while using the Designer view, or directly after connecting? And was this a fresh installation of Surrealist?

This issue appears to affect very few users making it difficult to debug, so any information you can provide will help!

**Comment by TimMensch** [comment]
Pretty much immediately after connecting. It just crashed out before I could do anything. It didn't work in Firefox, which is why I tried the app. Finally got it working in Chrome.

**Comment by macjuul** [comment]
I will close this issue for now as I can not find any clear cause. It may have already been resolved by changes made over the past months.

If anyone does run into this issue again feel free to open a new issue
