### ISSUE TITLE
Can't connect to remote database after upgrading to v2.0

### ISSUE THREAD

**Issue by mimib00** [surrealdb/surrealist#197]
**Describe the bug**
I just installed v2.0 on M1 2021 MacBook Pro and for some reason, I can't connect to my remote database. before it was working just fine but now it's not working

**To Reproduce**
Just click connect and an error "Connection failed" appears.

**Expected behavior**
it should connect to my remote database

**Environment:**
 M1 2021 MacBook Pro

**Comment by laldevfr** [comment]
Hi, same issue as you.
I have a surrealdb running in a DigitalOcean droplet  : `SurrealDB command-line interface and server 1.3.1 for linux on x86_64`
and with Surrealist V2.0 (M1 2021 Macbook ai) i can't connect to it (To noticed with http endpoint signin it's work fine) ?

**Comment by laldevfr** [comment]
To noticed, i config https on my remote server and after it's work fine.

**Comment by macjuul** [comment]
Were you using the web app or the desktop app to make connections?

**Comment by laldevfr** [comment]
for me it's the desktop app.

**Comment by Micnubinub** [comment]
Same on MacOS, desktop app, `1.4.2`
Anyone have any pointers on a config that works for putting surreal behind `nginx`? this seems to not be working
<img width="578" alt="image" src="https://github.com/surrealdb/surrealist/assets/4921356/df6dc5ba-09ec-4235-95eb-4dea42f3831b">

**Comment by laldevfr** [comment]
it's work me with : 
`/etc/nginx/proxy_params`
```
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```
And location : 
```
location /  {
          proxy_pass http://0.0.0.0:8000;
          include proxy_params;        
  }
```
For now i didn't use a subpath like /db because it's not working for me.

**Comment by mimib00** [comment]
@macjuul I'm using the 

> Were you using the web app or the desktop app to make connections?

I'm using Desktop app and connecting to this database was working fine on older versions but when I installed this v2.0 it stopped working

**Comment by macjuul** [comment]
Could you check if the logging console contains any errors?

Instructions on how to open can be found [here](https://surrealdb.com/docs/surrealist/getting-started/settings-and-customisation#opening-the-developer-console)

**Comment by Micnubinub** [comment]
Ah, it looks like surreal is removing the `/db`, so what should be `domain.com/db/version` & `domain.com/db/rpc` becomes `domain.com/version` `domain.com/version` & `domain.com/rpc`

**Comment by mimib00** [comment]
> include proxy_params;

This is the screenshot of the errors I got.
![Screenshot 2024-04-24 at 9 02 34 PM](https://github.com/surrealdb/surrealist/assets/83797689/94aea5df-05e0-402e-9f8e-a022f84cdbe0)

**Comment by ReziaBanks** [comment]
Currently facing the same issue
![Screenshot 2024-04-24 at 5 45 47 PM](https://github.com/surrealdb/surrealist/assets/44085898/2bcd8a59-19a8-4a90-ac6b-736e81c2c558)

**Comment by mimib00** [comment]
I was able to fix it by just reconfiguring my Nginx file
