### ISSUE TITLE
API Docs navigation could use some refinement

### ISSUE THREAD

**Issue by cabaucom376** [surrealdb/surrealist#199]
**Describe the bug**
I first noticed an issue when going to API Docs>SurrealML that it showed I was navigated to "Full-text search". I then realized this was because the navigation logic was based on the scroll position within single page doc. As the indicator seems to be based on what section is at the top of the screen it never allows "SurrealML" to hit said trigger.

![image](https://github.com/surrealdb/surrealist/assets/104145051/2eecf78a-9dfb-4989-a7ec-41b5917cb74e)

I then also noticed that while navigating between categories all sense of navigation disappears very temporarily leading to seemingly no focused item in-between categories. For example while scrolling between "Databases" and "Authentication", as Databases leaves the view the selected indicator vanishes. This breaks the UX flow in my opinion. Being extremely nit picky I know I'm sorry.

![image](https://github.com/surrealdb/surrealist/assets/104145051/88e6bfdc-933d-442d-9fa3-d217e5b909dc)

**To Reproduce**
Steps to reproduce the first behavior:
1. Go to 'API Docs'
2. Click 'SurrealML'

Steps to reproduce the second behavior:
1. Go to 'API Docs'
2. Click 'Databases'
3. Scroll to where it just leaves the screen
4. Observe the lack of selection indicator

**Expected behavior**
I expect that when I scroll all the way to the bottom 'SurrealML' becomes highlighted. I also expect that whenever you transition between categories it either places a selection indicator on the category itself, or the first item within it.

EDIT: I am running the macOS version of the software, Mac M1 pro

**Comment by macjuul** [comment]
While I cannot solve this issue entirely, I have added an increased padding to the bottom of the API docs. This should at least reduce the problem, and additionally improve the readability of the final topic
