### ISSUE TITLE
Features missing from the monaco editor

### ISSUE THREAD

**Issue by vitorTheDev** [surrealdb/surrealist#207]
**Describe your feature request**
Some features from the 1.x.x version are missing due to the removal of monaco in favour of codemirror. Out of all missing features, three stand out to me:
1. no `ctrl + / comment` command: it used to be easy to comment current line or all lines in selection with this command
2. no placing of `()` around selected text: before, you coud select some text then hit `shift + (` to place parenthesis around selection. Somehow it's currently working for `[` and `{`.
3. ~~no multiple cursor support: before you could `alt + click` to place multiple cursors and type to edit multiple places at once.~~ It's `ctrl + click`

These were great features that I and a few others miss from the old editor. If possible, it would be nice if they were implemented in the new editor aswell.

**Are you willing to contribute this feature?**
Yes. Tho I'm not very familiar with codemirror, but I can try to help. Number 2 could be implemented with a custom [extension](https://codemirror.net/docs/guide/#extension).

**Comment by vitorTheDev** [comment]
Looking at the docs for codemirror I found that [togglecomment](https://codemirror.net/docs/ref/#commands.toggleComment) is already a feature and should be working...

**Comment by macjuul** [comment]
Thank you for reporting these! If you run into more functionality you are missing from the old editor please do let me know again!

**Comment by vitorTheDev** [comment]
All issues fixed!
