### ISSUE TITLE
BUG - App crashes when moving table in designer view

### ISSUE THREAD

**Issue by Jacob26502** [surrealdb/surrealist#216]
**Describe the bug**
The App & Website crash when letting go of a table in the explorer while still moving the mouse.
React minified Error 185: 
```Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.```

**To Reproduce**
1. Go to [https://surrealist.app/designer](https://surrealist.app/designer)
2. Load the "Surreal Deal" demo dataset, alternatively create an empty table
3. Go to designer view, try and move any table with your mouse, but let go of the table while the mouse pointer is in motion
![image](https://github.com/surrealdb/surrealist/assets/57222813/0cbd387b-362f-44f5-a758-70e76c2532aa)

**Expected behavior**
The app should not crash when moving a table in the explorer view.

**Environment:**
Happens on both a fresh copy of the website and the desktop Tauri version

Platform: Web
Navigator: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Version: 2.0.2
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true

**OR**

Platform: Desktop
OS: Windows_NT
Architecture: x86_64
WebView: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
Version: 2.0.2
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true

**Comment by macjuul** [comment]
I'm currently unable to reproduce this issue myself on MacOS

**Comment by Icaruk** [comment]
Dragging fast crashes.

![](https://i.imgur.com/3ofkOwM.gif)

```
Platform: Desktop
OS: Windows_NT
Architecture: x86_64
WebView: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0
Version: 2.0.2
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true
```
![image](https://github.com/surrealdb/surrealist/assets/10779469/dc9f8b82-9d46-4efb-9196-8cddaca42a08)

**Comment by macjuul** [comment]
This issue should be fixed in the next patch release, however if you do still run into this error feel free to re-open the issue
