### ISSUE TITLE
Export Database does not do anything on the web version in case "Include Records" is selected

### ISSUE THREAD

**Issue by induras** [surrealdb/surrealist#218]
**Describe the bug**
When trying to export a database with records included, nothing happens.
When deselecting "Include Records" the download pops up immediately and the export works.

**To Reproduce**
1. Go to https://surrealist.app/designer
2. Load the "Surreal Deal" demo dataset
3. Go to explorer view, click on "Export Database" and select "Include Records"
4. Nothing happens

**Expected behavior**
Records can be exported as well when using the "Export database" feature.

**Environment:**
```
Platform: Web
Navigator: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Version: 2.0.2
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true
```

**Comment by PSmouz** [comment]
This is also the case for the native macOS version.
