### ISSUE TITLE
`Format Query` removes the commented queries

### ISSUE THREAD

**Issue by AyushChothe** [surrealdb/surrealist#222]
**Describe the bug**
`Format Query` removes the commented queries

**To Reproduce**
1. Write a query
2. Comment it 
3. Write another query 
4. Press `Format Query`

**Expected behavior**
`Format Query` should not remove commented queries

**Environment:**
```
Surrealist: Version 2.0.2 (20240424.110210)
```

**Comment by macjuul** [comment]
This is an unfortunate limitation of how the formatter works, as we parse the queries into surrealdb and use the built-in formatter as result.

I have changed the formatter so when a selection is active, only the highlighted text will be processed. This means you can format individual queries without losing all your comments
