### ISSUE TITLE
Missing depend on debian testing (trixie)

### ISSUE THREAD

**Issue by johansmitsnl** [surrealdb/surrealist#226]
**Describe the bug**
surrealist: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory.

Similar issue with #203

**To Reproduce**
1. Install the amd64 deb `sudo dpkg -i surrealist_2.0.3_amd64.deb`

**Expected behavior**
Start the application and have a depend so that dpkg complains.

**Environment:**

Debian testing with no openssl 1.x available. Only libssl3.

**Comment by tacheometry** [comment]
For the AUR package I was able to add `openssl-1.1` as a dependency, maybe there is a similar solution for Debian? Both packages use the `.deb` file. But I agree that it should be built for openssl 3.

**Comment by johansmitsnl** [comment]
@tacheometry it is absent. But version 3 is available in stable releases of Debian and Ubuntu. So that is best compatible on all versions of Linux.

**Comment by johansmitsnl** [comment]
Also the new releases Ubuntu 24.04 does nog have libssl1. https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=libssl1&searchon=all
