### ISSUE TITLE
Cannot create record in record explorer view.

### ISSUE THREAD

**Issue by welpie21** [surrealdb/surrealist#233]
**Describe the bug**
Cannot create record in record explorer view.

**To Reproduce**
1. Go to explorer view
2. Click on the "plus" in the record explorer ( with the tooltip: new record )
3. Select a table
4. Leave record id empty or you manually put an id in
5. You either fill in the content or you can leave as it is.
6. Press "create record"
7. It doesn't create

**Expected behavior**
When creating the record via the record explorer view it should make the record after you press the "create record" button.

**Environment:**
```
Platform: Desktop
OS: Windows_NT
Architecture: x86_64
WebView: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
Version: 2.0.3
Flags: featureFlags: true, models_view: true, apidocs_view: true, themes: true, newsfeed: true
```

**Comment by malcolm-alex-dev** [comment]
I am having this same problem on mac as well.

**Comment by andradei** [comment]
Same problem on Arch linux.
