### ISSUE TITLE
remove field from a table

### ISSUE THREAD

**Issue by mrpanam** [surrealdb/surrealist#234]
**Describe the bug**

i have a table product with a column ( field) risks, that i want to remove

1. Go to 'query' and execute
remove field risks on table product

**Expected behavior**
field should be removed from table

**Environment:**

Platform: Desktop
OS: Windows_NT
Architecture: x86_64
WebView: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
Version: 2.0.3
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true

```

**Comment by macjuul** [comment]
How are you currently checking which fields are defined in a table? Additionally, does it work when executing the same query via the CLI?

**Comment by mrpanam** [comment]
see below

![image](https://github.com/surrealdb/surrealist/assets/16197186/8cd7cecf-f7db-43f7-8142-742fea81c97f)

![image](https://github.com/surrealdb/surrealist/assets/16197186/29cae21d-60c5-44da-8bfc-0f78928cc7ba)

**Comment by macjuul** [comment]
This is actually how the REMOVE statement works in SurrealDB, as it will only update your schema, not your data. If you want to remove the fields from your records you can run the following query

```
UPDATE product UNSET risks;
```
