### ISSUE TITLE
Ability to update saved queries more easily

### ISSUE THREAD

**Issue by cabaucom376** [surrealdb/surrealist#240]
**Describe your feature request**
While architecting my databases I find myself aggressively saving my query modifications. Currently when you save a query it gets added to your list of saved ones, this is really useful, but I find the editing process to be cumbersome when working with a large set of queries and wanting to update them. This is the process right now:
1. Select your whole query
2. Copy it
3. Navigate to saved queries
4. Locate the query to update
5. Right click
6. Edit query
7. Select whole query that is saved
8. Paste
9. Save

I imagine a world where there is a simpler process. Just for illustration, when you save a query the star that you save it with becomes solid. Whenever you modify the query there are two more buttons near the star, save and discard. Something like this would be a massive quality of life feature that would improve my workflow drastically.

**Are you willing to contribute this feature?**
No, I would love to but I'm currently knee deep in my own project with limited time already.

**Comment by macjuul** [comment]
The saved query editor will now fully support SurrealQL similar to the main query view editor. While I currently do not have plans to synchronise query tabs to saved queries, I'll continue to consider ways to improve the query saving workflow going forward
