### ISSUE TITLE
Surrealist requires too many mandatory connection variables

### ISSUE THREAD

**Issue by OmanF** [surrealdb/surrealist#242]
When trying to create a connection, `Surrealilst`, web UI for certain, I couldn't get the installed app to work on my machine, requires the following *mandatory* connection variables to be supplied:

* Connection URL (consisting of protocol and address)
* Namespace
* Database
* (On the `root` authentication system) username
* Password

However, in its most basic form of spinning up a `SurrealDB` server, following the official documentation to the letter, a server is spun up that has only a URL and an initial user, that is **not** necessarily the server's administrator.

It is thus the case that when trying to connect to the spun-up server - one can't, because all five arguments listed above are all required, while the server itself only has two of them.  
The connection button will simply remain inactive until all five arguments are supplied (even if it means supplying false data/credentials that will cause the connection attempt to fail, e.g. a password on a server was spun up without setting one; supplying NS/DB where the server was spun-up without defining them first; etc.)

It should be the case that for all connection and authentication modes, the only mandatory arguments are the URL and username (which are the only mandatory arguments when spinning the server up).

**Comment by macjuul** [comment]
This is working as intended, I would recommend reading our [getting started guide](https://surrealdb.com/docs/surrealdb/introduction/start) to gain an understanding of how to make connections using Surrealist

- Both namespace and database can be set to anything, as these will be created automatically by the database once you start defining resources
- The generated initial user is in fact a root user, which you can authenticate with using the default selected "Root" authentication mode
- When starting a database you must specify a password when specifying a user, hence it is required

While namespace and database is optional in the CLI, it is currently required in Surrealist as these are both necessary for Surrealist to perform any functionality.
