### ISSUE TITLE
Create scope user command

### ISSUE THREAD

**Issue by Odonno** [surrealdb/surrealist#245]
**Describe your feature request**

Add a (shortcut) command to create a scope user:

1. Provide a form with variables infered from the SIGNUP scope function
2. Execute SIGNUP function of the scope and handle success/failure

![image](https://github.com/surrealdb/surrealist/assets/6053067/8b148e7a-7fce-400f-8040-bc335b404db5)

**Are you willing to contribute this feature?**

I can work on it, if needed.

**Comment by macjuul** [comment]
Implemented in version 2.0.5
