### ISSUE TITLE
Feature: Connect to a server without specifying a namespace or database.

### ISSUE THREAD

**Issue by alan-strickland-red** [surrealdb/surrealist#246]
**Describe your feature request**
It would be beneficial to be able to explore the namespaces and databases instead of having to specify them in the connection.

1. When connecting using root make the namespace and database name optional.
2. Extend the UI so an active namespace and database can be selected.

This then also leads the possibility of creating namespaces and databases.

**Are you willing to contribute this feature?**
Yes although I don't know when I would get the time to do it so if someone else has the capacity its a feature I would love to see.

**Related pull request (if applicable)**
N/A

**Comment by macjuul** [comment]
This has been implemented in #394
