### ISSUE TITLE
<bytes> in query crashes Surrealist

### ISSUE THREAD

**Issue by dbaudisch** [surrealdb/surrealist#249]
**Describe the bug**
`<bytes>` crashes Surrealist

**To Reproduce**
1. Run `<bytes> "Whatever";` in Query pane
2. Surrealist crashes
3. ???
4. No Profit :(

**Expected behavior**
To not crash

**Environment:**
Platform: Desktop
OS: Windows
Architecture: x86_64
WebView: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0
Version: 2.0.4
Flags: featureFlags: true, models_view: true, apidocs_view: true, themes: false, newsfeed: false

**Comment by abonshan** [comment]
I've got the same problem but have some things to add:
When creating a record with a bytes field, the record is added to the database and is visible in the explorer.

Querying the record results in another crash as I have described here: #270 

**Environment**
Platform: Desktop
OS: Windows_NT
Architecture: x86_64
WebView: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0
Version: 2.0.5
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true

**Comment by kearfy** [comment]
This seems to be happening because of an issue reported here: https://github.com/aaronhuggins/cbor-redux/issues/35

**Comment by kearfy** [comment]
Fixed in 23f520f60a0db8e9febad49577bbec018d6e2860
