### ISSUE TITLE
Stale connection

### ISSUE THREAD

**Issue by hammo92** [surrealdb/surrealist#250]
**Describe the bug**
If the surrealist application is left connected without sending a query for a prolonged period the connection displays as connected but queries cannot be sent. 

The user must manually reconnect by restarting the application or by re-saving the connection details to trigger a reconnect.

**To Reproduce**
Leave a the surrealist application connected without sending a query

**Expected behavior**
Surrealist to update the connection status and display the connect button

**Environment:**
Platform: GNU/Linux
OS: Ubuntu 23.10
Architecture: x86_64
WebView: 124.0.6367.78
Version: 23.10
Flags: featureFlags: true, models_view: true, apidocs_view: true, themes: false, newsfeed: false

**Comment by armandoradan** [comment]
I have the same problem with the windows app. The easiest way to reproduce is to cut the connection manually and connect it after a while. It will not detect the change in the connection and does not respond correctly. queries would not be sent and explorer view is either empty or shows fixed old data. When this happens, I have to either restart the application or change the connection to sandbox or another connection and then connect to my main destination again.
