### ISSUE TITLE
Surrealist depends on libwebkit2gtk-4.0-37, but its replaced by libwebkit2gtk-4.1-0

### ISSUE THREAD

**Issue by lukas-kd** [surrealdb/surrealist#255]
**Describe the bug**
Cant install or open the *.deb package of surrealist.
It will result in the error that there is no libwebkit2gtk-4.0-37 found (because Ubuntu 24.04 has libwebkit2gtk-4.1-0).

**To Reproduce**
1. Install Ubuntu 24.04
2. Download the 2.0.5-deb file from Releases
3. Install it

**Expected behavior**
I can install it with the libwebkit2gtk-4.1-0 package.

**Environment:**
```
1. Ubuntu 24.04
2. Surrealist 2.0.5
3. Surreal 1.4.2
```

**Comment by ThatsNasu** [comment]
Same problem here. i found a possible workaround for now [here](https://github.com/bambulab/BambuStudio/issues/3973#issuecomment-2085476683).

**Comment by birraasmile** [comment]
temporary workaround that worked for me:
Install:
[](https://answers.launchpad.net/ubuntu/noble/amd64/libjavascriptcoregtk-4.0-18/2.43.3-1)
[](https://answers.launchpad.net/ubuntu/noble/amd64/libwebkit2gtk-4.0-37/2.43.3-1)

then install surrealist
[](https://github.com/surrealdb/surrealist/releases/download/surrealist-v2.0.5/surrealist_2.0.5_amd64.deb)

Got it from:
[](https://github.com/clash-verge-rev/clash-verge-rev/issues/866#issuecomment-2073876022)

**Comment by birraasmile** [comment]
temporary workaround that worked for me:
Install:
https://answers.launchpad.net/ubuntu/noble/amd64/libjavascriptcoregtk-4.0-18/2.43.3-1
https://answers.launchpad.net/ubuntu/noble/amd64/libwebkit2gtk-4.0-37/2.43.3-1

then install surrealist
https://github.com/surrealdb/surrealist/releases/download/surrealist-v2.0.5/surrealist_2.0.5_amd64.deb)

Got it from:
https://github.com/clash-verge-rev/clash-verge-rev/issues/866#issuecomment-2073876022

**Comment by macjuul** [comment]
This should be fixed in the next release
