### ISSUE TITLE
Scrollbars missing

### ISSUE THREAD

**Issue by gregzuro** [surrealdb/surrealist#256]
**Describe the bug**
There are no (vertical) scrollbars in the query pane or the results pane (in combined and individual modes). 

**To Reproduce**
Do a query with enough results...

**Expected behavior**
scroll bar!

**Environment:**
Platform: Desktop
OS: Linux
Architecture: x86_64
WebView: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15
Version: 2.0.4
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true

**Comment by macjuul** [comment]
Closing as it cannot be reproduced internally and there has not been further activity on this issue
