### ISSUE TITLE
Surrealist has trouble handling a Polygon

### ISSUE THREAD

**Issue by Dhghomon** [surrealdb/surrealist#257]
**Describe the bug**
"Received invalid binary data" when trying to use a Polygon.

**To Reproduce**

Use a query that uses a Polygon, such as:

```
RETURN {
  type: "Polygon",
  coordinates: [[
    [-0.03921743611083, 51.88106875736589],
    [30.48112752349519, 50.68377089794912],
    [23.66174524001544, 42.94500782833793],
    [ 1.92481534361859, 41.69698118125476]
  ]]
};
```

Or a MultiPolygon:

```
UPDATE university:oxford SET locations = {
	type: "MultiPolygon",
	coordinates: [
		[
			[ [10.0, 11.2], [10.5, 11.9], [10.8, 12.0], [10.0, 11.2] ]
		],
		[
			[ [9.0, 11.2], [10.5, 11.9], [10.3, 13.0], [9.0, 11.2] ]
		]
	]
};
```

Interesting behaviour: 

* The CLI works fine
* No crash if you put the Polygon into a function

```
RETURN geo::centroid( {
  type: "Polygon",
  coordinates: [[
    [-0.03921743611083, 51.88106875736589],
    [30.48112752349519, 50.68377089794912],
    [23.66174524001544, 42.94500782833793],
    [ 1.92481534361859, 41.69698118125476]
  ]]
});
```

**Expected behavior**
Should return what the CLI does

**Environment:**

1.4.0 for windows on x86_64

And on the web version:

Platform: Web Navigator: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0 Version: 2.0.5 Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true

**Comment by macjuul** [comment]
Fixed in https://github.com/surrealdb/surrealist/commit/23f520f60a0db8e9febad49577bbec018d6e2860
