### ISSUE TITLE
Progress indicator when running long query

### ISSUE THREAD

**Issue by hariangr** [surrealdb/surrealist#258]
**Describe your feature request**
When running a query in Surrealist right now, there's no indication on 'working in progress'. The only indication that something was happening is the `Query X (duration in second)` message at the top of result window. When running long query, there's no loading indicator, so it's not rare for me to run a query multiple times

**Are you willing to contribute this feature?**
No

PS. counting number of rows in surrealdb took me around 30ish seconds for 80 thousands record, `SELECT COUNT() FROM table GROUP ALL`... is it normal?

**Comment by macjuul** [comment]
To answer your question, counting records is currently not optimised, however we intend to fix this in the near future. This would also speed up the explorer view in Surrealist as side effect.

As for displaying a loading indicator, I fully agree and will see what can I do
