### ISSUE TITLE
Do not scan tables when clicking on them

### ISSUE THREAD

**Issue by ioannist** [surrealdb/surrealist#262]
**Describe your feature request**
When clicking on the table, surrealist seems to be scanning all records. This is problematic for large databases with over 100K pages. In many cases, we have to restart surrealist and even surrealdb itself due to the volume of  the request. Instead, you could put a default LIMIT, either in terms of records or request time, and end your pagination with ....

**Are you willing to contribute this feature?**
No

**Comment by sourabpramanik** [comment]
@ioannist Surrealist does have a default limit of 25. It will not query for more than 25 records unless specified otherwise

**Comment by kearfy** [comment]
@sourabpramanik while that is true, I believe @ioannist here is affected by the query that retrieves the total table count. On SurrealDB's side, we're still improving these kind of queries, I'm not sure how we can best improve this scenario at the moment, but we'll have a think about it!

**Comment by ioannist** [comment]
Thanks. Sometimes, I've also noticed that if you click on (large) table A and then immediately on (small) table B, you will get table B and then, after a while, table A will load and replace it. This is a separate issue but also related to big tables.
