### ISSUE TITLE
Auto complete for user defined functions

### ISSUE THREAD

**Issue by Micnubinub** [surrealdb/surrealist#263]
**Describe your feature request**
Suggestions for user defined functions similar to the way tables get suggested after you type `fn`:
<img width="388" alt="image" src="https://github.com/surrealdb/surrealist/assets/4921356/8fedd9d9-577b-4238-9961-793ac9c2e4dd">

Oh and maybe some params and vars in scope when you type `$`?

**Are you willing to contribute this feature?**
No

**Comment by kearfy** [comment]
Added in [9d116d7](https://github.com/surrealdb/surrealist/commit/9d116d7f4b736b3cd0f45d18ec07f53ddf199548)
<img width="385" alt="image" src="https://github.com/surrealdb/surrealist/assets/17960250/b0629a60-ee3c-49d9-be75-bf51767bd393">
