### ISSUE TITLE
Adding INCLUDE ORIGINAL to a changefeed causes Surrealist to semi-freeze

### ISSUE THREAD

**Issue by Dhghomon** [surrealdb/surrealist#266]
**Describe the bug**
Adding INCLUDE ORIGINAL to a changefeed causes Surrealist to freeze up for a while.

**To Reproduce**
Try the example that we have in the 

```
REMOVE TABLE reading;
DEFINE TABLE reading CHANGEFEED 3d INCLUDE ORIGINAL;

-- Create some records in the reading table
CREATE reading SET story = "Once upon a time";
CREATE reading SET story = "There was a database";
UPDATE reading SET story = story + "!";

SELECT * FROM reading;

-- Replay changes to the reading table
SHOW CHANGES FOR TABLE reading SINCE 1 LIMIT 10;
```

No error is shown, but Surrealist will just sit there. Interestingly it isn't an outright freezing as the rest of the app continues to work, including the Run query button. It works again after reloading.

(The same behaviour happens both on the web version and desktop app, and this all works on the CLI)

**Expected behavior**
The query should display.

**Environment:**
Platform: Web
Navigator: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0
Version: 2.0.5
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true

and

Platform: Desktop
OS: Windows_NT
Architecture: x86_64
WebView: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0
Version: 2.0.5
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true

**Comment by macjuul** [comment]
Closing as clarified by https://github.com/surrealdb/surrealdb/issues/4268#issuecomment-2205816055

Support for INCLUDE ORIGINAL has been hidden from the UI for now
