### ISSUE TITLE
Querying bytes field crashes Surrealist

### ISSUE THREAD

**Issue by abonshan** [surrealdb/surrealist#270]
**Describe the bug**
Querying a bytes field results in a crash.

**To Reproduce**
1. Run `SELECT bytes_field FROM table;`.
3. Surrealist crashes with 'Received invalid binary data' message.

**Expected behavior**
No crash

**Environment:**
```
Platform: Desktop
OS: Windows_NT
Architecture: x86_64
WebView: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0
Version: 2.0.5
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true

```

**Comment by macjuul** [comment]
Closing in favor of #249
