### ISSUE TITLE
Cannot type into any field that is not a modal

### ISSUE THREAD

**Issue by NathanFrund** [surrealdb/surrealist#277]
**The bug**

After launching Surrealist, everything looks fine until I try to type in any field that is not in a modal; Query, Explorer, Designer, etc.

The text widget appears to take focus but the act of typing inputs no text.

Upon opening the web inspector a recurring error revolving around *http://localhost:8000/rpc* appears.

**To Reproduce**
1. Go to the release page and download the appropriate DMG.
2. Start Surrealist and open the web inspector.

**Environment:**
```
Surrealist Version 2.0.6 (20240514.150408)

macOS Monterey 12.7.4
```

![image](https://github.com/surrealdb/surrealist/assets/871821/5fb2c158-ff27-448c-be5a-689be5c11302)

**Comment by jjazzme** [comment]
same issue

**Comment by thf24** [comment]
same here on macOS Monterey. makes the app not really useable unfortunately (and was almost a reason not to use Surreal DB for a new project).

**Comment by jjazzme** [comment]
> same here on macOS Monterey. makes the app not really useable unfortunately (and was almost a reason not to use Surreal DB for a new project, I really like the database overall though so still decided to go with it).
> 
> The issue has been present also already for the last 2 months+ since I first installed Surrealist and no updates so far resolved it.

its so sad!

**Comment by macjuul** [comment]
Hello everyone, first of all my apologies for this issue taking so long to resolve. After multiple attempts looking into this I cannot personally, nor cannot find anyone in the vicinity that can reproduce this issue. For this reason I'll need a set of questions answered so I can further scope down the possible cause of this.

- Does this happen only in the desktop app and safari, or also other browsers?
- What is the version of the browser you are using? In case of the desktop app, please use your version of Safari
- Does this affect SurrealQL editors or also seemingly normal text inputs?
- Is it correct inputs do gain focus visually, however only the input refuses to work?
- Does this affect all input, or do certain characters/keys still work?

I'll be diverting time to focus on this issue as I understand how frustrating it must be. Since I cannot reproduce or test it myself, I will share binaries as soon as I have potential fixes in place.

**Comment by thf24** [comment]
It seems to be a Safari issue (using the Desktop app), if I open the sandbox with Firefox it works fine. Opening the sandbox (https://surrealist.app/query) in Safari has the same issue as the Desktop app for me.
Safari Version 15.4 (17613.1.17.1.6)
The inputs look correct and get focus, but only Enter, Tab and Backspace seem to be working.
I'm updating my MacOS to Sonoma now, maybe this will fix it.

**Comment by thf24** [comment]
works fine on Sonoma now (Desktop App)!

**Comment by macjuul** [comment]
Very interesting, that's a big help!

**Comment by macjuul** [comment]
For those experiencing this issue, I have made [some changes](https://github.com/surrealdb/surrealist/compare/main...fix/safari-input) which may solve this issue. I'll attach the binaries to this comment for testing.

[Surrealist_2.1.1_aarch64.dmg.zip](https://github.com/user-attachments/files/15546217/Surrealist_2.1.1_aarch64.dmg.zip)
[Surrealist_2.1.1_x64.dmg.zip](https://github.com/user-attachments/files/15546218/Surrealist_2.1.1_x64.dmg.zip)

**Comment by jjazzme** [comment]
> For those experiencing this issue, I have made [some changes](https://github.com/surrealdb/surrealist/compare/main...fix/safari-input) which may solve this issue. I'll attach the binaries to this comment for testing.
> 
> [Surrealist_2.1.1_aarch64.dmg.zip](https://github.com/user-attachments/files/15546217/Surrealist_2.1.1_aarch64.dmg.zip) [Surrealist_2.1.1_x64.dmg.zip](https://github.com/user-attachments/files/15546218/Surrealist_2.1.1_x64.dmg.zip)

already better! In the query window, text is now entered. But, for example, I cannot change the name of the "New connection".
![image](https://github.com/surrealdb/surrealist/assets/35768966/f659a831-0d8d-4951-8744-5c3a38f5bf87)

**Comment by NathanFrund** [comment]
@macjuul, my experience appears to be like that of @jjazzme.

I'm able to enter queries (yes!), but I also cannot change/edit the name of a connection.

**Comment by jjazzme** [comment]
> @macjuul, my experience appears to be like that of @jjazzme.
> 
> I'm able to enter queries (yes!), but I also cannot change/edit the name of a connection.

It is possible that other editable fields are affected.

**Comment by NathanFrund** [comment]
@jjazzme, you're right.

After a bit more exploration, I found that I cannot edit the name of a table, for example.

![image](https://github.com/surrealdb/surrealist/assets/871821/bcb0d74d-c953-4c7f-80da-add8fd91deca)

**Comment by macjuul** [comment]
@NathanFrund the table name is actually the one input which isn't supposed to be editable (yet!). I'll update the visuals to make it look less like an input as to prevent further confusion

@jjazzme @NathanFrund just looking to confirm, input fields and editors are working now, however editable inline text (such as the connection name) is not?

**Comment by macjuul** [comment]
I have made some further adjustments which hopefully resolve the remaining issues with editable inline text. Here are some new binaries for testing

[Surrealist_2.1.1_aarch64.dmg.zip](https://github.com/user-attachments/files/15568257/Surrealist_2.1.1_aarch64.dmg.zip)
[Surrealist_2.1.1_x64.dmg.zip](https://github.com/user-attachments/files/15568258/Surrealist_2.1.1_x64.dmg.zip)

**Comment by NathanFrund** [comment]
@macjuul, thanks!

I was able to fire up the app and replicate my work in the web app.

I'm looking forward to what's to come.

**Comment by jjazzme** [comment]
@macjuul, thank you, everything works great

**Comment by macjuul** [comment]
Fantastic! Thank you all for the patience and feedback, I'll have this fix included in the next patch release
