### ISSUE TITLE
Cannot import SurMlFile either with Python or Direct Import

### ISSUE THREAD

**Issue by ReginaPulsifi** [surrealdb/surrealist#278]
**1) Try to import SurMlFIle using Python but FAILED.** Please take note that the url is really starting with wss.

```python

dict_lst = {"work_interest_model": "wi_bestmodel_pca768_3layers_6mins.onnx",
            "work_value_model": "wv_bestmodel_pca768_3layers_4mins.onnx",
            "work_style_model": "ws_bestmodel_pca768_2layers_10mins.onnx"}

for name, file in dict_lst.items():
    SurMlFile.upload(
    	path=f"../Model/{name}.surml",
    	url="wss://pulsifi-knowledge-graph.fly.dev/ml/import",
    	chunk_size=36864,
    	namespace="fs_dev",
    	database="fs_dev",
    	username="root",
    	password="root"
    )
```
**Error which I got:**
thread '<unnamed>' panicked at src[/python_apis/storage.rs:282:51](http://localhost:8888/python_apis/storage.rs#line=281):
called `Result::unwrap()` on an `Err` value: hyper::Error(Connect, "invalid URL, scheme is not http")
PanicException: called `Result::unwrap()` on an `Err` value: hyper::Error(Connect, "invalid URL, scheme is not http")

**2) Try to upload SurMlFIle through the app but also FAILED.** I select the surrealmlfile which I want to import into the surrealdb and clicked open. After that nothing show up in the Models folder.
<img width="1063" alt="image" src="https://github.com/surrealdb/surrealist/assets/97146067/041f1e46-95b0-49f1-bb69-327c2043dbe3">
<img width="806" alt="image" src="https://github.com/surrealdb/surrealist/assets/97146067/aef2c9e8-ae18-43fb-a976-6221bbfe707c">
<img width="357" alt="image" src="https://github.com/surrealdb/surrealist/assets/97146067/09429096-bf37-4c85-9542-56ab01dda297">
<img width="575" alt="image" src="https://github.com/surrealdb/surrealist/assets/97146067/001535e2-0443-4d94-a35c-d13baced64e1">

**My Environment**
Platform: Desktop
OS: Darwin
Architecture: aarch64
WebView: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)
Version: 2.0.6
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true

**Comment by macjuul** [comment]
This doesn't appear to be specifically Surrealist related to I'll close this issue and recommend creating an issue on the SurrealML or surrealdb repositories instead.

That said, the uploading of surrealML models is currently only supported over HTTP(S) connections, so the URL passed to `SurMlFile.upload` must have the http or https protocol. Hopefully that solves it! 🙂

**Comment by ReginaPulsifi** [comment]
Hello, thanks for the reply~ Now the issue is solved using the HTTP protocol
