### ISSUE TITLE
Open Surrealist via URL Schema

### ISSUE THREAD

**Issue by ManAnRuck** [surrealdb/surrealist#288]
Here is a refined version of your GitHub feature request:

---

**Describe your feature request**

Hi,

I would like to request the ability to open the Surrealist app via a URL scheme, such as `surrealist://SOME_CONFIGURATION`. This feature would streamline the process of launching Surrealist with a specific configuration immediately after starting a database. 

In my application, I have a script that could generate this link, allowing me to directly open Surrealist with the correct configuration. This enhancement would significantly improve my development workflow.

Moreover, extending the URL scheme to support parameters like `surrealist://SOME_CONFIGURATION?name=CONFIG_NAME&protocol=PROTOCOL&…` would enable the creation or modification of connection settings dynamically. This would eliminate the need for individual developers to manually adjust settings, enhancing efficiency and consistency across the team.

EDIT: Maybe `SOME_CONFIGURATION`could be a screen or you have some better ideas ;)

**Are you willing to contribute this feature?**
Yes, I am willing to contribute to the implementation of this feature.

**Related pull request (if applicable)**
- [ ] no pr created yet

## Depends on
- [x] https://github.com/tauri-apps/tauri/issues/323
- [ ] [Roadmap 2.0](https://github.com/orgs/tauri-apps/projects/11/views/2)

**Comment by macjuul** [comment]
This will be possible to implement once support for Tauri 2 is completed (https://github.com/surrealdb/surrealist/pull/291)

The current plan is to allow deeplinks to dispatch intents, which are the same actions made available to the command palette. This means you'll be able to deep link to specific views, dialogs, and other actions

**Comment by macjuul** [comment]
I have drafted a PR which implements deeplink support, including opening specific views and dispatching intents. The list of currently available intents can be found [here](https://github.com/surrealdb/surrealist/blob/main/src/util/intents.tsx#L3)

Just to get a clear picture, you mention passing `SOME_CONFIGURATION`. I'm not entirely sure what you mean with this. Are you referring to creating connections via deeplinks?

**Comment by ManAnRuck** [comment]
> Just to get a clear picture, you mention passing `SOME_CONFIGURATION`. I'm not entirely sure what you mean with this. Are you referring to creating connections via deeplinks?

Yes, `SOME_CONFIGURATION` is not the best way to do it I think, but at the end yes. it would be awesome to open a connection without a previous existing configuration.
