### ISSUE TITLE
"Create record + "

### ISSUE THREAD

**Issue by zenic-master** [surrealdb/surrealist#296]
The "Create record + " button has dynamic height.
As long as the number of lines does not exceed the height of Contents, it is displayed correctly.
When the number of lines is greater, the "Create record + " button disappears...

![Screenshot 2024-05-24 181455](https://github.com/surrealdb/surrealist/assets/62288574/7ab1d2ec-d34c-47c4-89cc-404f04221e03)
![Screenshot 2024-05-24 182047](https://github.com/surrealdb/surrealist/assets/62288574/ba07ffb0-2ec9-4043-ac3c-016af5bc0594)

**Comment by macjuul** [comment]
Fixed in the next release!
