### ISSUE TITLE
Large decimal cast into number results in invalid binary data

### ISSUE THREAD

**Issue by Dhghomon** [surrealdb/surrealist#303]
**Describe the bug**
That invalid binary data message that causes Surrealist to need a reload. Might be related to this: https://github.com/surrealdb/surrealdb/issues/4105

**To Reproduce**
RETURN <number> 5555555555555555555555dec;

**Expected behavior**
5555555555555555555555dec; (same as the CLI)

**Environment:**
```
Platform: Desktop
OS: Windows_NT
Architecture: x86_64
WebView: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0
Version: 2.0.6
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true

```

**Comment by macjuul** [comment]
Fixed in 23f520f60a0db8e9febad49577bbec018d6e2860
