### ISSUE TITLE
Invalid Content-Type for HTTPS requests

### ISSUE THREAD

**Issue by EtienneBruines** [surrealdb/surrealist#304]
**Describe the bug**
When configuring a connection that uses the HTTPS scheme (potentially also HTTP, havent' tested), there is a HTTP POST request to `/mypath/rpc`. This HTTP request has a request HTTP header `Content-Type: 
text/plain;charset=UTF-8`. This results in a HTTP response saying `invalid HTTP header (content-type)` with status 400 Bad Request. 

Regardless of whether or not the SurrealDB (v1.5.1) should be able to parse this correctly (https://github.com/surrealdb/surrealdb/issues/4106), the correct value would be `application/json`. 

The payload for this HTTP request is this, so I'm assuming it's part of the "version checking" logic:
```json
{"id":1,"method":"version"}
```

**To Reproduce**
1. Configure a connection with "HTTPS"
2. Open the browser developer tools `Network` tab
3. Try to connect

**Expected behavior**
A HTTP 200 response (or better yet, a correct `Content-Type` request header). 

**Environment:**
Platform: Web
Navigator: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Version: 2.0.6
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true

**Comment by EtienneBruines** [comment]
Potentially already fixed in the dev version, since this seems to use `application/cbor`?

**Comment by macjuul** [comment]
This may now be resolved in the 2.1 release. Could you confirm this?

**Comment by EtienneBruines** [comment]
@macjuul Confirmed, awesome!
