### ISSUE TITLE
Microsoft Defender SmartScreen prevented an unrecognized app from starting

### ISSUE THREAD

**Issue by cope** [surrealdb/surrealist#316]
Probably won't make people feel good when they see this 😞 

![image](https://github.com/surrealdb/surrealist/assets/112515/bc03d65b-9b09-4c11-8a5b-1eb593a8bdac)

**Comment by macjuul** [comment]
We are currently working on implementing code signing for our Windows binaries, much like they already are on MacOS, which should prevent this screen from appearing. This process is however significantly more time consuming compared to Apple code signing, hence we have yet to roll this out.

Note that securing our applications is a top priority for us, hence we intend to roll out signed binaries as soon as we can
