### ISSUE TITLE
Saved Query title not updating in the main Queries list

### ISSUE THREAD

**Issue by dodanex** [surrealdb/surrealist#320]
**Describe the bug**
1. BUG: In the Query area: Editing a saved query title from the Saved Queries list, it does not update the title in the main Query list (but updates ok in the saved query list). 
2. FEATURE: In the Query area: For saved queries add a "Edit query" link in the right click context menu for a quick edit.

**To Reproduce**
Try to rename the title of a saved query and see that the title is not updating in the main Queries list.

**Expected behavior**
To update the title of saved queries in main Queries list.

**Environment:**
Platform: Desktop
OS: windows
Architecture: x86_64
WebView: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0
Version: 2.1.0
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true

**Comment by macjuul** [comment]
This appears to be working as intended. The names of queries in the query list are independent from saved queries and can be renamed after creation
