### ISSUE TITLE
Redo shortcut missing

### ISSUE THREAD

**Issue by LucyEgan** [surrealdb/surrealist#324]
**Describe the bug**
Currently undo via `Ctrl + Z` and redo via `Ctrl + Y` are available, but redo via `Ctrl + Shift + Z` is missing

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'query editor'
2. Press `1` (1), `[BACKSPACE]`, `2` (2), `[BACKSPACE]`, 3 (3)
3. Press `Ctrl + Z` (), `Ctrl + Z` (1)
4. Press `Ctrl + Shift + Z` (Should be 2)

**Expected behaviour**
Pressing `Ctrl + Shift + Z` should be the same as `Ctrl + Y`

**Environment:**
Platform: Desktop
OS: Windows_NT
Architecture: x86_64
WebView: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0
Version: 2.0.0
Flags: featureFlags: true, models_view: true, apidocs_view: true, themes: true, newsfeed: true

**Comment by macjuul** [comment]
This should be working correctly in the latest release

**Comment by LucyEgan** [comment]
@macjuul Is "latest release" referring to a upcoming version as this is still the case in `2.1.2`?

Running version `2.1.2` shortcut `Ctrl + Shift + Z` does nothing.

**Comment by macjuul** [comment]
Strange, it's working fine for me on 2.1.2 on both the desktop app (MacOS) and web

**Comment by LucyEgan** [comment]
I'll have a check on osx web and windows web when I get a moment.
Is the shortcut bound to meta + shift + z? Cus that would be correct for osx and not Windows or are both bound?

**Comment by Sandros94** [comment]
> Strange, it's working fine for me on 2.1.2 on both the desktop app (MacOS) and web

Not on windows (or at least for me), both desktop and web

**Comment by LucyEgan** [comment]
Can confirm it worked fine on OSX but not windows

**Comment by macjuul** [comment]
Thanks for checking! I have implemented a fix which will be included in the next release
