### ISSUE TITLE
Delay when typing on submitting query so old query gets ran instead

### ISSUE THREAD

**Issue by LucyEgan** [surrealdb/surrealist#326]
**Describe the bug**
When typing and submitting the query not slowly it will send the old query(what it was 200-300ms ago)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Query view'
2. Type 1, 200-300ms delay then press `Ctrl+Enter`
3. It will treat it as the query was empty
4. Type 1, wait 1 second, replace with 2 and then press `Ctrl+Enter` within 300ms and it will return `1` instead of `2`

**Expected behaviour**
To update the active query as you type rather than a 200-300ms debounce
Or instant fetch the current query to send rather than what it was 200-300ms ago

**Environment:**
Platform: Desktop
OS: windows
Architecture: x86_64
WebView: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0
Version: 2.1.0
Flags: featureFlags: true, models_view: true, apidocs_view: true, themes: true, newsfeed: true

**Comment by macjuul** [comment]
This has actually already been improved for the upcoming 2.1.1 patch release, as the debounce on editors has been lowered to 50ms 🙂

**Comment by LucyEgan** [comment]
@macjuul hahah noticed it months ago and the day I finally mention it 🤣 perfect thanks
