### ISSUE TITLE
Modifying permissions in the designer fails

### ISSUE THREAD

**Issue by caleblamro** [surrealdb/surrealist#329]
**Describe the bug**
Modifying permissions in the designer tab doesn't actually modify the permissions.

**To Reproduce**
1. Open the surrealist web version (I haven't tried the desktop version)
2. Select any table and attempt to modify the permissions
3. Click "save changes" to save your modifications
4. Once the slideover closes, open it again and see that the permissions have not changed. You can also query 'INFO FOR DB' to verify the permissions have not changed

**Expected behavior**
Permissions are properly modified

**Environment:**
```
Platform: Web
Navigator: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Version: 2.1.0
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true
```

**Comment by macjuul** [comment]
I suspect there may have been an issue in the permission syntax, however the designer drawer would perviously not handle and display errors correctly. I've improved this where errors are now correctly displayed, allowing you to further debug potentially invalid values

**Comment by caleblamro** [comment]
![Screenshot 2024-06-07 093357](https://github.com/surrealdb/surrealist/assets/96218685/37e7685f-4429-4836-a6a9-9ff9e4f5cfda)
![image](https://github.com/surrealdb/surrealist/assets/96218685/7407f4d4-9197-4456-8b5f-546a78de5382)
Thank you for doing that! Having error messages when the permissions are invalid will be awesome! I've attached some photos of the modifications I'm making to show you exactly what's going on. I don't believe the syntax is incorrect since when I make the modifications in the query tab, they work correctly. For this example I'm simply adding another scope to the select permissions on one of my tables. The first screenshot shows me adding `OR $scope = 'user'` to the select permissions, and the second screenshot shows the permissions after I've clicked 'Save changes'. I'd love to help with this issue, so please let me know if there's anything you'd like me to try!

**Comment by caleblamro** [comment]
Ahh I see. I assumed since the `WHERE` clause wasn't in there to being with, I didn't need to add it. Once again, I really appreciate your help and the time you took to look into this for me.
