### ISSUE TITLE
won't launch

### ISSUE THREAD

**Issue by GiveMeFox** [surrealdb/surrealist#331]
**Describe the bug**
after update it doesn't launch as in there is a process in the background but there's no window or anything that actually shows that the app has started
![image](https://github.com/surrealdb/surrealist/assets/74460065/ed6da320-a0cf-4b83-9e92-cba344ceda1e)

**To Reproduce**
1. install and run Surrealist v2.1.0 (Surrealist_2.1.0_x64_en-US.msi)

**Expected behavior**
I wanted to be able to see a window open after I run the program

**Environment:**
```
Edition: Windows 11 Pro
Version: 21H2
```

**Comment by macjuul** [comment]
Is this using Surrealist 2.1.1? Additionally, does the web app (surrealist.app) work correctly in the Edge browser?

**Comment by macjuul** [comment]
This issue appears to be surpassed by #356 on which I have replied with possible solutions

If this isn't the case and it is unrelated feel free to re-open!
