### ISSUE TITLE
Explorer - Array of objects doesn't work

### ISSUE THREAD

**Issue by jboureux** [surrealdb/surrealist#341]
**Describe the bug**
When I want to create a record in a schemaful table with an array of objects properties, the record explorer doesn't create the objects content. I think this should be investigated to see if the problem comes from the `array<object>` type or if this is deeper.

**To Reproduce**
Create a table with a field of `array<object>` type,
Try to create a record with objects in the array
Save the record and witness the absence of content in the objects (see screens after)

**Expected behavior**
Objects should have their content

**Environment:**
```
MacOS Sonoma,
Surrealist 2.1.2

(clicking the version number doesn't work for me 🥲)
```

**Screenshots**

![image](https://github.com/surrealdb/surrealist/assets/62116434/cf9acc85-ec2c-4c51-b106-bc82950d4216)
Simple schemaful table made for the test 

![image](https://github.com/surrealdb/surrealist/assets/62116434/d47a36a2-67c6-4f43-90e4-21b2ccf73db3)
record i'm trying to create

![image](https://github.com/surrealdb/surrealist/assets/62116434/4640cb50-95f3-4f92-9215-84b96f34e0c1)
result I get

**Comment by macjuul** [comment]
This is intended behaviour as by default you are expected to define the inner object fields as part of your schema as well. You can however bypass this and allow flexible object contents by marking the field as `FLEXIBLE` 😃
