### ISSUE TITLE
Mac installer won't work for 2.1.2

### ISSUE THREAD

**Issue by fmquaglia** [surrealdb/surrealist#346]
Downloaded the DMG installer on a 3,3 GHz 6-Core Intel Core i5 iMac, with Sonoma 14.5 (23F79)

**To Reproduce**

1. Go to https://github.com/surrealdb/surrealist/releases
2. Download Surrealist_2.1.2_aarch64.dmg
3. Open the downloaded installer
4. It will show the app icon with a canceled on top (typically for incompatible apps).

**Expected behavior**
The installer would allow the app to be dragged to the Applications folder.

**Environment:**
```
3,3 GHz 6-Core Intel Core i5 iMac, 
Sonoma 14.5 (23F79)
```

![GIF Recording 2024-06-18 at 3 06 15 PM](https://github.com/surrealdb/surrealist/assets/678453/388fea04-8b50-45af-aa76-85b3f60ede36)

**Comment by macjuul** [comment]
It looks like you downloaded the installer for Apple Sillicon chips, while you need the Intel compatible installer. You can easily [download the right version](https://surrealdb.com/surrealist?download) from our website!

**Comment by fmquaglia** [comment]
You were right, in the releases page I missed the expanding link "see al releases", where the x64 installer was listed. Thanks for pointing it out @macjuul
