### ISSUE TITLE
Keep Query variables panel open by default

### ISSUE THREAD

**Issue by hgoona** [surrealdb/surrealist#359]
1. It would be great to pin open the Variables panel Open by default, on the Query page.

2. Commenting out a variable in the Query page seems to be deleted when Surrealist is closed and re-opened. In the Query editor itself, commented code appears to be retained which is great - can we extend this behaviour to the Query Variables panel as well?

**Comment by macjuul** [comment]
Regarding your first point, do you mean you want Surrealist to remember the open state of the panel and persist it across restarts?
