### ISSUE TITLE
breakdown when invoke encoding::base64::decode 

### ISSUE THREAD

**Issue by classLfz** [surrealdb/surrealist#360]
**Describe the bug**
When I query with `RETURN encoding::base64::decode("MjMyMw");`, the surrealist application alert the information `Received invalid binary data`.

**To Reproduce**
1. init surrealdb;
2. open surrealist with a new query;
3. input `RETURN encoding::base64::decode("MjMyMw");`;
4. click `Run query` button;

**Expected behavior**
Message: `Received invalid binary data`

**Environment:**
```
1. surrealist version: 2.1.2;
2. surrealdb version: 1.5.3;
```

**Comment by macjuul** [comment]
This was fixed in Surrealist 2.1.4 and later versions 😁
