### ISSUE TITLE
Add a context menu item to view the table designer mode from explore

### ISSUE THREAD

**Issue by LucyEgan** [surrealdb/surrealist#361]
**Describe your feature request**
Add "View structure/table/info" here (in explorer)
<img width="166" alt="image" src="https://github.com/user-attachments/assets/649ae977-5520-4fed-b841-b720d59ed7f3">

which would load the side bar from "Designer"
<img width="386" alt="image" src="https://github.com/user-attachments/assets/b1f9e07f-8ea8-4bfe-b9d0-7879eb034f94">

**Comment by macjuul** [comment]
This has been implemented in #394
