### ISSUE TITLE
.rpm not published

### ISSUE THREAD

**Issue by horvbalint** [surrealdb/surrealist#364]
**Describe the bug**
In the version [v2.1.2](https://github.com/surrealdb/surrealist/releases/tag/surrealist-v2.1.2) there were some new installer types published, for example a .rpm installer. I was very happy to see this, because it is pretty cumbersome to manage appimages. Sadly in the latest 2 versions no rpm installer was published and the built-in auto updater also fails to install the new versions. 

**To Reproduce**
Check the published assets in the linked release and the following two releases.

**Expected behavior**
Since it was once available I would expect it to be available still. This is why I am categorizing this as a bug and not as a new feature.

**Comment by macjuul** [comment]
This issue is now [fixed upstream](https://github.com/tauri-apps/tauri-action/pull/873)

The next release of Surrealist should include RPM binaries again!
