### ISSUE TITLE
Export uses UPDATE instead of RELATE for relations

### ISSUE THREAD

**Issue by Dhghomon** [surrealdb/surrealist#367]
**Describe the bug**
A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.

**To Reproduce**

CREATE person:one, person:two;
RELATE person:one->likes->person:two;

**Expected behavior**

The same as the content below except TABLE DATA: likes should have `RELATE person:one->likes:f575c5dev8ueiruqt5sl->person:two` instead of `UPDATE likes:f575c5dev8ueiruqt5sl CONTENT { id: likes:f575c5dev8ueiruqt5sl, in: person:one, out: person:two }`.

(Note: the CLI generates output with RELATE so users can still export by using the CLI and then import into Surrealist, after which there are no problems.)

-- ------------------------------
-- Export generated by Surrealist on 2024-07-22T03:35:56.396Z
-- ------------------------------

OPTION IMPORT;

-- ------------------------------
-- TABLE: likes
-- ------------------------------

DEFINE TABLE likes TYPE ANY SCHEMALESS PERMISSIONS NONE;

-- ------------------------------
-- TABLE: person
-- ------------------------------

DEFINE TABLE person TYPE ANY SCHEMALESS PERMISSIONS NONE;

-- ------------------------------
-- TRANSACTION
-- ------------------------------

BEGIN TRANSACTION;

-- ------------------------------
-- TABLE DATA: likes
-- ------------------------------

UPDATE likes:f575c5dev8ueiruqt5sl CONTENT { id: likes:f575c5dev8ueiruqt5sl, in: person:one, out: person:two };

-- ------------------------------
-- TABLE DATA: person
-- ------------------------------

UPDATE person:one CONTENT { id: person:one };
UPDATE person:two CONTENT { id: person:two };

-- ------------------------------
-- TRANSACTION
-- ------------------------------

COMMIT TRANSACTION;

**Environment:**

Online, sandbox

**Comment by macjuul** [comment]
Surrealist uses the schema to determine whether a table is a regular table or edge table. Using the designer view you can change the table type of the desired table to "Relation", after which exports will start writing `RELATE` statements

This is something we will consider improving in the future!
