### ISSUE TITLE
Connection refresh

### ISSUE THREAD

**Issue by sanjeethboddi** [surrealdb/surrealist#368]
**Describe your feature request**
I was using surrealist to try out multiple surrealdb versions running locally using docker. When I kill the container and spawn another, the surrealist has no option to refresh the connection. 

**Are you willing to contribute this feature?**
Yes, I would like to add a refresh button which will close the current connection and spawn a new connection.

**Related pull request (if applicable)**
No PR. Would love to contribute.

**Comment by macjuul** [comment]
The connection system has been overhauled in #394, including the option to manually reconnect. This should resolve your issue!
