### ISSUE TITLE
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer

### ISSUE THREAD

**Issue by simeonnv** [surrealdb/surrealist#373]
**Describe the bug**
The surrealist desktop app is blank. I can still press buttons but i cant see anything

**To Reproduce**
Opening it just after installation

specs:
Linux Mint 22 Cinnamon right out of the box
NVIDIA Corporation TU116 [GeForce GTX 1650]
with a NVIDIA driver 535
using surrealist version 2.1.5

**The error**

if i open the app in a console the error
```AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer```
gets spammed

![Screenshot from 2024-07-29 19-30-26](https://github.com/user-attachments/assets/2048beb7-87ff-46ba-afaf-4f0fd180262e)

**Comment by macjuul** [comment]
This is a known issue on Linux systems using NVIDIA graphics.

You can find more information [here](https://github.com/surrealdb/surrealist/issues/276#issuecomment-2203244788)
