### ISSUE TITLE
Automatically format functions when opened

### ISSUE THREAD

**Issue by caleblamro** [surrealdb/surrealist#374]
**Describe your feature request**
When opening the function editor, the code for the function seems to be minified (similar to how they show up when running `INFO FOR DB`. I think it would be a nice feature to have this formatted when the editor is opened.

**Are you willing to contribute this feature?**
Yes, I'd love to contribute. I'm aware there's already a query formatter used in the application, so my intuition is to reuse that and simply format the function contents on load with useEffect.

**Related pull request (if applicable)**
N/A

**Comment by macjuul** [comment]
This has been implemented in #376
