### ISSUE TITLE
Strange formatting on tooltips for nested objects in explorer

### ISSUE THREAD

**Issue by Xkonti** [surrealdb/surrealist#378]
**Describe the bug**
In the Explorer tab, the nested objects display as eg. `Object(3)`. When hovered they show a tooltip. As seen on the screenshot below, the indentation formatting goes all wonky making the value impossible to see, even though there's enough room:

![image](https://github.com/user-attachments/assets/c9b83c5a-b285-44b9-89bf-a7bf0ba68f5e)

The full item value:

```surql
{
	id: item:desk,
	is_container: true,
	is_package: false,
	name: 'Desk',
	total: {
		quantity: 1dec,
		unit: unit:x,
		universal_quantity: 1dec
	}
}
```

**To Reproduce**
1. Create record with nested object and some values
2. Go to explorer
3. Navigate to table
4. Hover over the object value

**Environment:**
```
Windows 11, Desktop app
Version: 2.1.5
Flags: feature_flags: true, models_view: true, apidocs_view: true, themes: false, newsfeed: true, database_version_check: true, highlight_tool: false, surreal_compat: v2, changelog: auto
```

**Comment by macjuul** [comment]
This has been fixed in #394
