### ISSUE TITLE
Refresh issue

### ISSUE THREAD

**Issue by mahbubabbas** [surrealdb/surrealist#379]
**Describe the bug**
1. There is NO refresh option.
2. The connection is lost after some time. 

**To Reproduce**
1. Go to 'Connections'
2. Change the existing connection to new server
3. It does NOT refresh to show new connection

**Expected behavior**
The entire window must be refreshed show dbs from new server.

**Environment:**
```
Windows 11, Surrealdb 1.5.2
```

**Comment by mahbubabbas** [comment]
Any updates on this issue

**Comment by mahbubabbas** [comment]
I am worried why others are silent as all of them facing this issue. And no one is addressing this issue at all.

**Comment by macjuul** [comment]
The connection system will be overhauled in the next release, including fully automatic reconnecting, which will likely solve your issue 🙂

**Comment by macjuul** [comment]
The improved connection system has been implemented in #394 and introduces automatic reconnecting. This should resolve your issue!
