### ISSUE TITLE
GraphQL Client with Schema showcase

### ISSUE THREAD

**Issue by itsezc** [surrealdb/surrealist#391]
**Describe your feature request**
With the addition of GraphQL to Surreal, it would be nice to view the schema in Surrealist and send queries and mutations (and perhaps save named queries similar to SQL).

Inspiration can be taken from Apollo GraphQL Studio which is considered the best GraphQL IDE in the market.

**Are you willing to contribute this feature?**
Unfortunately, I cannot due to time constraints

**Related pull request (if applicable)**

**Comment by macjuul** [comment]
Initial support for a GraphQL view has been implemented in #394. While currently it does not offer introspection, documentation, and auto completion, these are features we intend to implement in the near future
