### ISSUE TITLE
Add option to create/open a connetion to a local file

### ISSUE THREAD

**Issue by matthewjnield** [surrealdb/surrealist#398]
**Describe your feature request**

I think Surrealist would greatly benefit from having the option to create and open a connection to a SurrealDB database stored in a local file at an arbitrary location on the user's computer, in addition to the current options shown in the picture below (in-memory, HTTP, WebSockets, etc.):

![image](https://github.com/user-attachments/assets/e8361121-5495-4c6b-adc5-6340d7dd6e1c)

Currently, if a SurrealDB database is created and maintained through the `surreal` CLI tool and/or programming SDKs and stored in a local file on the user's computer, I do not believe it is possible to explore and query that SurrealDB database from Surrealist. If it is possible, it is not obvious to me how to do so.

Adding this feature would bring the following benefits for SurrealDB users:

* The convenience and flexibility of being able to interact with SurrealDB databases stored on the user's computer as a local file using a combination of various methods, i.e. not only programmatically from the command line and through SDKs, but also through a handy GUI interface.

* The ability to create and query playground/sandbox/dummy databases which can be kept separate and returned to at any point for those learning about and testing SurrealDB using Surrealist,

* Surrealist would be brought closer to being able to do everything that the `surreal` CLI tool can do, and the Surrealist connection selection menu would be more analogous to the options of the `surreal` CLI tool for specifying the storage option of a SurrealDB instance, such as the following:

Starting a SurrealDB instance stored in-memory (currently supported by Surrealist):

```console
surreal sql --endpoint memory
```

Starting a SurrealDB instance stored in a local file, without specifying the key-value store to be used (to be deprecated in SurrealDB 2.0)  (currently not supported by Surrealist):
```console
surreal sql --endpoint file://path_to_database_file.db
```

Starting a SurrealDB instance stored in a local file, using RocksDB as the key-value store (currently not supported by Surrealist):
```console
surreal sql --endpoint rocksdb://path_to_database_file.db
```

Starting a SurrealDB instance stored in a local file, using SurrealKV as the key-value store (to be supported by the upcoming SurrealDB version 2.0) (currently not supported by Surrealist):
```console
surreal sql --endpoint surrealkv://path_to_database_file.db
```

**Are you willing to contribute this feature?**
Yes. However, I would need to become more familiar with the Surrealist codebase in order to determine the requirements to implement this feature and contribute to the related changes.

**Related pull request (if applicable)**
N/A

**Comment by matthewjnield** [comment]
After reading #8, I now see that this can be done by altering a setting (option shown below).

In my opinion, it would make sense to have this option moved to the main connections menu so that it is located with the rest of the storage options and thus more obvious to users.

Additionally, it would be ideal if the file location could be selected through a pop-up file GUI explorer window rather than inserted manually, but I have read that the Tauri  framework currently does not fully support such a window that can access the entire filesystem.

![image](https://github.com/user-attachments/assets/a0f3d53d-63d1-4cd6-bb9c-3414d7f9b1b5)

**Comment by macjuul** [comment]
This is currently not possible since Surrealist runs as a client-side application with no direct access to the file system. The easiest way to do this is by using the integrated database serving functionality in Surrealist Desktop.

From the "Database Serving" tab in the Settings screen you can set "Storage mode" to the desired value, and enter the path to the database
