### ISSUE TITLE
Min window size too large?

### ISSUE THREAD

**Issue by LucyEgan** [surrealdb/surrealist#402]
**Describe the bug**
Currently the min window size is set too large.
When running at 75% window scale, it still would be usable at a min size of around 600 so i dont think we should force a min size on to the end user.
https://github.com/surrealdb/surrealist/blob/eee97beb46e61023c0d55476169d362d3237761b/src-tauri/src/main.rs#L119

**To Reproduce**
1. Drag the window to right of screen to 1/2 or 1/3 the screen.

**Expected behavior**
Expect the window to take up 1/2 or 1/3 the screen as the application has plenty of visual space to continue working at this size.

**Environment:**
Version: 3.0.0-beta.1
Flags: feature_flags: false, query_view: true, explorer_view: true, graphql_view: true, designer_view: true, auth_view: true, functions_view: true, models_view: true, apidocs_view: true, cloud_view: true, themes: true, newsfeed: true, database_version_check: false, highlight_tool: false, legacy_serve: false, cloud_endpoints: production, cloud_access: false, changelog: hidden

**Comment by macjuul** [comment]
The current UI is not built to be responsive, hence the current minimum size which guarantees a comfortable user experience at 100% UI scaling.

I do intend on addressing this going forward, and ultimately allow Surrealist to be used at a mobile compatible size, however this may take time and multiple iterations
