### ISSUE TITLE
Bug: When LIVE SELECTing the Live Messages x minutes ago are all the same

### ISSUE THREAD

**Issue by LucyEgan** [surrealdb/surrealist#429]
### Describe the bug

<img width="253" alt="image" src="https://github.com/user-attachments/assets/31245561-ecb3-44a1-a1fb-30a4e9636631">

These live messages were across the last few minutes, when a new list message is added it gets the timestamp of the first live message rather than the current time it was received(and continues to tick forward from the oldest timestamp)

### Steps to reproduce

`LIVE SELECT a table`
Start Listening to those results

Cause a update to that table once every minute for 3 minutes and each will say 3 minutes ago

### Expected behaviour

With the above example each row should say
```
Just now
1 minute ago
2 minutes ago
```

### Surrealist Environment

Version: 3.0.0-beta.2
Flags: feature_flags: false, query_view: true, explorer_view: true, graphql_view: true, designer_view: true, auth_view: true, functions_view: true, models_view: true, apidocs_view: true, cloud_view: true, themes: true, newsfeed: true, database_version_check: false, highlight_tool: false, legacy_serve: false, cloud_endpoints: production, cloud_access: false, cloud_killswitch: true, changelog: hidden

### Contact Details

lucy.e@aspirecomps.co.uk

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by macjuul** [comment]
Fixed in #440
