### ISSUE TITLE
Bug: Saving a (lng, lat) point in an element breaks the table view of Surrealist

### ISSUE THREAD

**Issue by alhill** [surrealdb/surrealist#432]
### Describe the bug

If in any table is saved an element which contains a field with a type::point value, Surrealist crashes when trying to show the list view of this table. Reading the element and updating it works well from the query tab.

### Steps to reproduce

Make a query as ```UPDATE position:whatever MERGE {
    point: (1,2)
};``` and try to enter to the table "position" in Surrealist

### Expected behaviour

It should show the table view but instead of this crashes with this error 
![image](https://github.com/user-attachments/assets/02bc67f8-b1c3-4baf-8142-a1cdd79ca86a)

### Surrealist Environment

Surrealist 2.1.6
SurrealDB 1.5.3

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by macjuul** [comment]
This was fixed in #396 and will be included in the next release. Specifically, Surrealist crashes because integer coordinates are not supported and must be provided as decimal
