### ISSUE TITLE
Bug: Doesn't minimise when toggling to another application

### ISSUE THREAD

**Issue by vbasky** [surrealdb/surrealist#448]
### Describe the bug

When surrealist is open and I switch to another application, surrealist stays active and hides the other application from being viewed

### Steps to reproduce

Open Surrealist. Cmd + Tab to another application. Surrealist doesn't hide or minimise unless it is manually minimised. 

### Expected behaviour

Surrealist to hide on Mac automatically when switching

### Surrealist Environment

Version 3.0.0 (20240917.152315)

### Contact Details

vikram.bhaskaran@outlook.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by macjuul** [comment]
I cannot reproduce this myself on MacOS. Could it be that you accidentally enabled the "Always on top" option in `Settings > Behavior`?

**Comment by vbasky** [comment]
That was the case apologies. Will close the bug ticket. I had it turned on accidentally
