### ISSUE TITLE
Bug: Breadcrumb doesn't reflect namespace and databases

### ISSUE THREAD

**Issue by vbasky** [surrealdb/surrealist#449]
### Describe the bug

Breadcrumb menu doesn't reflect the exisiting namespace or database nor does it reflect after creating a new one

<img width="371" alt="image" src="https://github.com/user-attachments/assets/e38704ca-17a3-464e-a88f-07ca579fea35">

<img width="1040" alt="image" src="https://github.com/user-attachments/assets/cf73f8dd-2539-4b9c-a646-7b5a322d8e46">

### Steps to reproduce

Open Surrealist on Mac M1
Go to the open connections
Add new namespaces
Add new databases

### Expected behaviour

Surrealist should show the list of namespaces and databases

### Surrealist Environment

<img width="266" alt="image" src="https://github.com/user-attachments/assets/d0a4a553-ab55-4fc5-ae45-e7f28df13b03">

### Contact Details

vikram.bhaskaran@outlook.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by macjuul** [comment]
Could you clarify which authentication method you are using to connect to the database? You can find it in the edit connection dialog under the Authentication section. Additionally just to confirm, you are able to create namespaces/databases, however they don't appear in the dropdown menus?

**Comment by vbasky** [comment]
They seem to have been fixed in 3.0.2. I am able to view the namespaces and all the databases. When I create a namespace or database they seem to instantly appear. Happy to close this
