### ISSUE TITLE
Bug: Table designer doesn't allow table name updates

### ISSUE THREAD

**Issue by cabaucom376** [surrealdb/surrealist#450]
### Describe the bug

The inputs for editing table names in the table designer UI don't work.

### Steps to reproduce

Attempt to edit a tables name.

### Expected behaviour

Table name to properly edit and apply.

### Surrealist Environment

Version: 3.0.0
Flags: feature_flags: true, query_view: true, explorer_view: true, graphql_view: true, designer_view: true, auth_view: true, functions_view: true, models_view: true, apidocs_view: true, cloud_view: true, themes: true, newsfeed: true, database_version_check: true, highlight_tool: false, legacy_serve: false, cloud_endpoints: production, cloud_access: false, cloud_killswitch: true, changelog: auto

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by macjuul** [comment]
Editing the name of existing tables is currently not possible in Surrealist or SurrealDB, however we are planning on supporting this in a future release.

I'll redesign the UI to make the table name look less like an input as I fully understand the confusion and expectation to edit it!
