### ISSUE TITLE
Bug: Keep require to connect Database, while using root auth 

### ISSUE THREAD

**Issue by Stvchm9703** [surrealdb/surrealist#460]
### Describe the bug

when using the root user auth, should expect I can access the whole database engine in any ns / db.  
![image](https://github.com/user-attachments/assets/640cddce-4c26-44c4-9453-ad16d7291df3)

but it still cannot connect and fail to access via the Surrealist, and keep throwing the you must connect to a database

![image](https://github.com/user-attachments/assets/dcda0ae2-78e9-4b84-a688-485ab2a76d73)

let say I first-time run the database, and suppose none of namespace and database are created, I cannot control the engine in surrealdb

### Steps to reproduce

1. create a docker env
2. run the docker image 
3. back to Surrealist, and goto "connection"
![image](https://github.com/user-attachments/assets/31f174f6-319d-48f5-a2d8-7ad3688edd69)

4. select "Root" as Auth, input the access and root information 
5. try some query, and throwing "you must connect to a database"

### Expected behaviour

as the root access, should do any query without access any NS / DB

### Surrealist Environment

Surreal DB : v2.0.1

Version: 3.0.0
Flags: feature_flags: false, query_view: true, explorer_view: true, graphql_view: true, designer_view: true, auth_view: true, functions_view: true, models_view: true, apidocs_view: true, cloud_view: true, themes: true, newsfeed: true, database_version_check: true, highlight_tool: false, legacy_serve: false, cloud_endpoints: production, cloud_access: false, cloud_killswitch: true, changelog: auto

### Contact Details

stv.chm@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by macjuul** [comment]
The word "database" in these notifications may be slightly misleading, as what it actually means is the connection to the SurrealDB instance has not (yet) opened. If you hover over the connection name in the top left of the toolbar you will be able to see whether the connection is connected (indicated by a green dot), or not (either red or orange).

Once the connection is open, you should be able to execute queries freely without selecting a database, although keep in mind if you intend on referencing any tables, you will still need to select one which you can do via the dropdowns in the toolbar.
