### ISSUE TITLE
Feature: Middle mouse drag to create multiple cursors

### ISSUE THREAD

**Issue by LucyEgan** [surrealdb/surrealist#476]
### Is your feature request related to a problem?

Currently multiple cursors are supported but you need to `ctrl`+`click` each cursor which is fine when there's a few but after 5+ you get a need for a bit better way to do it 😅 

Webstorm has middle click drag to create multiple cursors/multiple selections
<img width="159" alt="image" src="https://github.com/user-attachments/assets/1aab113d-e39b-4790-9cf2-90ed24d41071">

### Describe the solution

In text editors allow middle click dragging to create multiple cursors, possibly multiple selections but that's less important.

### Are you willing to contribute this feature

No

### Surrealist Environment

Version: 3.0.2
Flags: feature_flags: true, query_view: true, explorer_view: true, graphql_view: true, designer_view: true, auth_view: true, functions_view: true, models_view: true, apidocs_view: true, cloud_view: true, themes: true, newsfeed: true, database_version_check: false, highlight_tool: true, legacy_serve: false, cloud_endpoints: production, cloud_access: false, cloud_killswitch: true, changelog: auto

### Contact Details

lucy.e@aspirecomps.co.uk

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by macjuul** [comment]
This is actually already supported by holding `alt`/`option` while selecting text, which turns the selection into a multi-line rectangle 🙂
