### ISSUE TITLE
Bug: inconsistent behavior when using RELATE ENFORCED 

### ISSUE THREAD

**Issue by agarfer1** [surrealdb/surrealist#481]
### Describe the bug

When creating a `TYPE RELATION` with the `ENFORCED` clause at the end, for example:

`DEFINE TABLE bought TYPE RELATION IN buyer OUT car ENFORCED;`

The exported schema becomes:

`[.....] ENFORCED SCHEMALESS PERMISSIONS NONE;`

And in the designer, when viewing the relation, the checkbox for "Enforce schema" is not ticked.

However, when checking that checkbox in the designer, and saving the changes, the exported schema becomes:

`[......] SCHEMAFULL PERMISSIONS NONE;`

### Steps to reproduce

1. Run the following query:

```
DEFINE TABLE bought TYPE RELATION IN buyer OUT car ENFORCED SCHEMALESS PERMISSIONS NONE;

CREATE car:ford;
CREATE buyer:James;
RELATE buyer:James->bought->car:ford;
```

2. Visualize the relation in the table designer, the "Enforce schema" checkbox won't appear ticked.
3. Export the DB.

4. Go back into the table designer, click in the "Enforce schema"  checkbox, save the changes.
5. Export this second version of the DB to see the differences.

### Expected behaviour

The checkbox should appear ticked even if the table is SCHEMALESS.

The behavior when using using ENFORCED from a query and from the visual editor should be the same, in my opinion the RELATION shouldn't turn SCHEMAFULL.

### Surrealist Environment

Version: 3.0.3
Flags: feature_flags: false, query_view: true, explorer_view: true, graphql_view: true, designer_view: true, auth_view: true, functions_view: true, models_view: true, apidocs_view: true, cloud_view: true, themes: true, newsfeed: true, database_version_check: true, highlight_tool: false, legacy_serve: false, cloud_endpoints: production, cloud_access: false, cloud_killswitch: true, changelog: auto

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by macjuul** [comment]
Support for the new `ENFORCED` keyword in the Designer will be available in the near future. The "Enforce schema" checkbox actually predates this keyword and is used to control the `SCHEMALESS`/`SCHEMAFULL` property on a table, but I totally understand how confusing this is!
