### ISSUE TITLE
Bug: Out of memory after submitting long queries

### ISSUE THREAD

**Issue by Xkonti** [surrealdb/surrealist#491]
### Describe the bug

For testing I'm pasting-in a 1.1 million lines long queries and execute then through Surrealist. After sending one or 2 queries like that, surrealist keeps soft-crashing with an out-of-memory message:

![image](https://github.com/user-attachments/assets/da2e7e67-ede9-4f84-9e0e-dbd35de2593a)

This continues to happen after a restart, possibly due to the queries still being in the query history (and trying to render the whole thing).

### Steps to reproduce

Here's the code that generates said 165MB query: https://github.com/Xkonti/surreal-benchmarks/blob/main/benchmarks/select_simple.ts

### Expected behaviour

No slowdowns of Surrealist, possibly showing a warning that the query won't be present in the query history due to it's size.

### Surrealist Environment

Can't get to the settings because Surrealist keeps crashing, but I remember it's v3.0.4 on Windows 11

### Contact Details

ben@xkonti.tech

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by macjuul** [comment]
Hey! I have been working on improvements to the query history drawer [in this PR](https://github.com/surrealdb/surrealist/pull/489) after watching one of your previous streams 😄 Hopefully that will improve memory usage as a result

**Comment by macjuul** [comment]
Fixed in #489
