### ISSUE TITLE
Bug: Cannot edit query name in firefox

### ISSUE THREAD

**Issue by varma02** [surrealdb/surrealist#500]
### Describe the bug

On the `Query` tab when I try to edit the name of a query it just selects the text. If I manually give the parent `<p>` element `contenteditable="true"` it works and it  remains after a refresh.

### Steps to reproduce

 1. Open https://surrealist.app in firefox
 2. Try to edit a query's name

### Expected behaviour

When I click on the name I can edit it.

### Surrealist Environment

Platform: Web
Navigator: Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0
Version: 3.0.5
Flags: feature_flags: false, query_view: true, explorer_view: true, graphql_view: true, designer_view: true, auth_view: true, functions_view: true, models_view: true, apidocs_view: true, cloud_view: true, themes: true, newsfeed: true, database_version_check: true, highlight_tool: false, legacy_serve: false, cloud_endpoints: production, cloud_access: false, cloud_killswitch: true, changelog: auto

### Contact Details

varma01@mail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by macjuul** [comment]
This appears to be caused by Firefox lacking support for `contenteditable="plaintext-only"`
