### ISSUE TITLE
Automatic update

### ISSUE THREAD

**Issue by AngeloCore** [surrealdb/surrealist#52]
Yeah, um, can you make the app only update itself, without downloading the new release every time? Thanks!

**Comment by macjuul** [comment]
While this would be a nice addition it is also quite a lot of work to implement at the moment so I'll keep this in mind for the future. Thanks!

**Comment by DcZipPL** [comment]
I would be able to implement it for you and make pull request soon. It shouldn't be hard :)
Thanks for Surrealist!

**Comment by macjuul** [comment]
This has now been implemented in Surrealist 2.0!
