### ISSUE TITLE
Bug: Invalid display of Geo Point

### ISSUE THREAD

**Issue by bordeux** [surrealdb/surrealist#520]
### Describe the bug

Data view displaying incorrectly GeoPoint. It uses longitude as latitude and latitude as  longitude.

Example:

Geo Point: (50.3348759, 18.890746)
View of the map:
<img width="660" alt="image" src="https://github.com/user-attachments/assets/5454d99f-05f6-4a51-9ba5-1cf9ddd24069">

View on list of items:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/81659a84-344d-4d2f-b5f2-cca651cf8932">

Related topics:
https://github.com/surrealdb/docs.surrealdb.com/issues/936
https://github.com/surrealdb/surrealist/pull/314#event-13101962467

### Steps to reproduce

1. Create new GeoPoint  (50.3348759, 18.890746)
2. See this data on explorer.

### Expected behaviour

It should show correct point on the map and correct position on data view. First item of touple should be used as lat, and second item from touple should be taken as long.

### Surrealist Environment

Version 3.0.7 (20241010.134301)

### Contact Details

admin@bordeux.net

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by macjuul** [comment]
This is working as intended as the format used within SurrealDB is (long, lat), in line with the [GeoJSON specification](https://geojson.org/). I have confirmed this format is respected across the SurrealDB core, JavaScript SDK, and Surrealist geography inspector.

It does appear the docs were recently erroneously updated to (lat, long), which we will revert soon. Hope that clarifies the topic!

**Comment by bordeux** [comment]
Thank you for update! :) Happy to hear one official way of storing it.
