### ISSUE TITLE
Bug: Cant import full Demo dataset

### ISSUE THREAD

**Issue by nickchomey** [surrealdb/surrealist#560]
### Describe the bug

When I import the [full](https://datasets.surrealdb.com/surreal-deal-store.surql) (not mini) Surreal Deal Store dataset, the tables are created but no data gets imported. I've tried it in Surrealist 3.0.8 on windows, chrome, microsoft edge, as well as importing via CLI using the command [in the docs](https://surrealdb.com/docs/surrealql/demo#import): `surreal import --conn http://localhost:8000 --user root --pass root --ns test --db test surreal-deal-store.surql`. Whether I use memory, sandbox, rocksdb etc doesnt matter.

Queries just return 
```
-------- Query 1 (100.001µs) --------

[]
```

![image](https://github.com/user-attachments/assets/a09c0932-8017-4096-9ae1-59f85834d87c)

If I import the mini dataset, it works fine. The issue is evidently with the full dataset.

### Steps to reproduce

Import dataset via surrealist, cli etc... 

### Expected behaviour

That the data shows up

## Windows 
Version: 3.0.8
Flags: feature_flags: false, query_view: true, explorer_view: true, graphql_view: true, designer_view: true, auth_view: true, functions_view: true, models_view: true, apidocs_view: true, cloud_view: true, themes: true, newsfeed: true, database_version_check: true, highlight_tool: false, legacy_serve: false, cloud_endpoints: production, cloud_access: false, cloud_killswitch: true, changelog: auto

## Chrome version 
Platform: Web
Navigator: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Version: 3.0.8
Flags: feature_flags: false, query_view: true, explorer_view: true, graphql_view: true, designer_view: true, auth_view: true, functions_view: true, models_view: true, apidocs_view: true, cloud_view: true, themes: true, newsfeed: true, database_version_check: true, highlight_tool: false, legacy_serve: false, cloud_endpoints: production, cloud_access: false, cloud_killswitch: true, changelog: auto

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexFrid** [comment]
Hey @nickchomey, thanks for pointing this out. These are known issues that were fixed in the mini dataset, but somehow got missed in the full dataset, will fix that now.
