### ISSUE TITLE
Bug/Accident: Surrealist freeze with 10s of thousands of databases 😄 

### ISSUE THREAD

**Issue by adaliszk** [surrealdb/surrealist#581]
### Describe the bug

I accidentally created more databases than I wanted, but in turn, run into an interesting issue where the Surrealist strait freezes up, and even after waiting a few minutes, it remains unusable. In my case, I had made about 50k schemaless tables, and I can see that the application tries to fetch the schema for all tables one by one, thus dealing with a lot of work that blocks user interaction.

### Steps to reproduce

- Make 1000+ tables, ideally 10k+
- Open the database with Surrealist
- Try to click around the navigation
- Try to execute a query

### Expected behaviour

While 50k tables are not intended, a few thousand tables should not cause UI application issues, as the application can only display one table at a time anyway.

### Surrealist Environment

Version: 3.1.1
Flags: feature_flags: false, query_view: true, explorer_view: true, graphql_view: true, designer_view: true, auth_view: true, functions_view: true, models_view: true, apidocs_view: true, cloud_view: true, themes: true, syntax_themes: false, newsfeed: true, database_version_check: true, highlight_tool: false, legacy_serve: false, cloud_endpoints: production, cloud_access: false, cloud_killswitch: true, changelog: auto

### Contact Details

adam@liszkai.dev

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by macjuul** [comment]
Hey! Surrealist isn't made to support tens of thousands of namespaces, databases, or tables at this time. I'll keep making performance improvements over time so who knows one day it will be supported 🙂 

Based on your comment I did improve the batch fetching of tables, so that might already make a slight difference!

**Comment by adaliszk** [comment]
Nice! I can't wait to make more tables by mistake. Of course, this is more of a funny accident report than a severe bug, but I figured it would be worth letting you know that it can happen. One other thing I think that could help is to add pagination on the tables sidebar; that way when there are just too many tables, at least the impact can be limited to one page worth only.
