### ISSUE TITLE
Add support for SurrealDB migrations

### ISSUE THREAD

**Issue by ansarizafar** [surrealdb/surrealist#88]
**Describe your feature request**
It would be great If can manage Database migrations with Surrealist. Migrations support can be added with https://github.com/Odonno/surrealdb-migrations

**Comment by macjuul** [comment]
I'm interested in researching the viability of this. Personally I don't have any experience with surrealdb-migrations, so could you give me some thoughts and examples on how this could be implemented in Surrealist and which benefits it provides?

Thanks!

**Comment by timyourivh** [comment]
@macjuul 

Hello, I'm also interested in having a migration feature like or similar like this.

Laravel has a pretty nice introduction of their implementation of database migrations on their documentation page:

> _"Migrations are like version control for your database, allowing your team to define and share the application's database schema definition. If you have ever had to tell a teammate to manually add a column to their local database schema after pulling in your changes from source control, you've faced the problem that database migrations solve."_
<sup>[source](https://laravel.com/docs/10.x/migrations#introduction)</sup>

Their approach involves creating a file for each database change, including both "up" and "down" methods for migrating and rolling back, respectively.

> could you give me some thoughts and examples on how this could be implemented in Surrealist

In this context, I would look something like this:

1. First, you create a migration. Usually a file (best readable when raw), but could be stored in an array as a sting as well. You would name them to reflect the changes it introduces. This is similar to a summary or message for a Git commit. For this example it would be something like: "Create user table" or "create_user_table".
1. It's important to have the ability to order migrations. Laravel accomplishes this by prefixing a timestamp before the migration name.
1. Inside a migration, you define the database changes that should be made when running the migration. These definitions are typically placed within an "up" section or method. It's content would contain the instructions, for this example:
    ```sql
    -- Create schemafull user table.
    DEFINE TABLE user SCHEMAFULL;

    -- Define some fields.
    DEFINE FIELD firstName ON TABLE user TYPE string;
    DEFINE FIELD lastName ON TABLE user TYPE string;
    DEFINE FIELD email ON TABLE user TYPE string
      ASSERT string::is::email($value);
    DEFINE INDEX userEmailIndex ON TABLE user COLUMNS email UNIQUE;
    ```
1. Additionally, the migration should define how to roll back changes in a "down" section or method, allowing for the reversal of changes made during the "up" phase. For this example, you could remove the table that was created in the "up" section:
    ```sql
    REMOVE TABLE article;
    ```
1. Now, you should have the ability to execute the migration. This action needs to be logged and monitored by saving an identifier or the migration's name, which can be stored in either a database or a file. This way the application remains aware of which migrations have been successfully executed, preventing the re-execution of the same migration(s).
1. If not satisfied with the result, you should have the option to "rollback" the migration, which should undo any changes made during the migration process.

In Laravel, migration management involves keeping track of executed migrations by batching them, allowing to roll back migrations in groups or batches.

> and which benefits it provides

By enabling the loading of migrations from a folder or file, we can remove the need for developers to create custom, framework-specific or language-specific migration tools. Instead, Surrealist could serve as a universal migration management solution for everyone, offering a more efficient and standardized approach. Additionally, a major benefit would be the ability to maintain a comprehensive record of data model changes and database modifications for the entire project. This would be possible by syncing the folder or file containing the migrations with the project's repository, ensuring data consistency and traceability.

In terms of UI, this could be represented as a list of migration entries loaded from the folder or file. Each entry in the list would show an indicator, making it clear which migration has been recognized as "migrated" or not.

Here are my thoughts on the matter, and I hope that this comment hasn't been a waste of anyone's time. While it would be fantastic to see this feature implemented, I also understand that the tool is already highly valuable in its current state, and adding such a feature may be a significant undertaking.

**Comment by macjuul** [comment]
Considering Surrealist has now joined SurrealDB officially, I am not currently looking to implement third party projects directly into the app. Additionally, there are plans to build official migration support in the future which would receive support in all our tooling

**Comment by timyourivh** [comment]
Actually, I am very satisfied with the import/export system! I decided to simply replace the migration structure with the export file (without the data of course). And this works flawlessly! The changes will be reflected in git which makes it possible to rollback using git. I can list many more things why this is a great change but to keep it brief:

Amazing work to all the collaborators who made this possible! ❤️ 🚀
